---
title: "National zoomss"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
library(raster)
library(sf)
library(tidyverse)
library(patchwork)

source(here::here("common.R"))
source(here::here("functions", "map_priorities.R"))
```

# Mapping resrouces

```{r mapping_resources}
theme_maps <- theme(axis.text.x = element_text(size = 6),
                    axis.text.y = element_text(size = 6),
                    axis.ticks = element_blank(),
                    axis.line = element_blank(),
                    axis.title.x = element_blank(),
                    axis.title.y = element_blank(),
                    legend.text = element_text(size = 6),
                    legend.text.align = 0,
                    legend.position = "bottom",
                    legend.background = element_rect(fill = NA, color = NA),
                    panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
                    panel.grid.minor = element_blank(),
                    panel.background = element_rect(fill = NA, color = NA), 
                    panel.border = element_blank(),
                    plot.background = element_rect(fill = NA, color = NA), 
                    plot.caption = element_text(hjust = 0.5))

global_cols <- c("#4575b4", "#74add1", "#abd9e9", "#e0f3f8", "#fee090", "#fdae61", "#f46d43", "#d73027", "#4575b4")

global_breaks <- c(0, 0.3, 0.5, 0.7, 0.8, 0.85, 0.9, 0.95, 1)

eez_with_land <- sf::st_read(file.path(emLab_shrd_data_dir, "marine-regions-EEZ-land-union-v3-202003", "EEZ_Land_v3_202030.shp")) %>% 
  sf::st_wrap_dateline(options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"), quiet = TRUE) %>% 
  sf::st_transform(crs(ocean_low_res_moll)) %>% 
  sf::st_simplify(dTolerance = 10000, preserveTopology = TRUE) %>% 
  janitor::clean_names()

eez <- sf::st_read(file.path(emLab_shrd_data_dir, "marine-regions-eez-v10", "World_EEZ_v10_20180221", "eez_v10.shp")) %>% 
  sf::st_wrap_dateline(options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"), quiet = TRUE) %>% 
  sf::st_transform(crs(ocean_low_res_moll)) %>% 
  sf::st_simplify(dTolerance = 10000, preserveTopology = TRUE) %>% 
  janitor::clean_names()

mpas_raster <- raster(file.path(emLab_project_dir, 
                                "data", "02_processed", "masks", "fully_highly_protected_reviewed_MPAs.tif"))

mpas_polys <- sf::st_read(file.path(emLab_project_dir, 
                                    "data", "02_processed", "masks", "fully_highly_protected_reviewed_MPAs.gpkg")) %>% 
      st_set_crs(st_crs(eez))
```

# Load global results

```{r}
bio_ranking <- raster(file.path(emLab_project_dir, "data", "03_output", "05_spp_wts_smts_provs_MPAs", "ranking_raster.tif"))
food_ranking <- raster(file.path(emLab_project_dir, "data", "03_output", "07_food", "ray", "ranking_raster_a2.tif"))
carbon_ranking <- raster(file.path(emLab_project_dir, "data", "03_output", "06_carbon", "ranking_raster_updated.tif"))
```

# 

```{r subset_raster}
subset_priorities_raster <- function(priorities_raster, iso3s, eez_file){
  
  roi_polygon <- eez_file %>% 
    filter(iso_sov1 %in% iso3s)
  
  roi_ranking <- priorities_raster %>% 
    crop(as(roi_polygon, "Spatial"), snap = "out") %>% 
    mask(as(roi_polygon, "Spatial"))
  
  names(roi_ranking) <- paste(paste(iso3s, collapse = "_"), "global_ranking", sep = "_")
  
  if(all(is.na(getValues(roi_ranking)))){
    
    warning('Raster is empty')
    
  } else {
    
    roi_ranking <- trim(roi_ranking)
    
  }
  
  return(roi_ranking)
  
}
```


```{r reproject_raster}
reproject_local_raster <- function(local_raster, method){
  
  roi_ranking_wgs84 <- local_raster %>% 
    projectRaster(crs = crs("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"), 
                  method = method, over = F)
  
  min_lon <- round(roi_ranking_wgs84@extent@xmin)
  
  max_lon <- round(roi_ranking_wgs84@extent@xmax)

  if(min_lon == -180 & max_lon == 180){

    roi_ranking_projected <- local_raster %>%
      projectRaster(crs = crs("+proj=merc +lon_0=150 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"),
                    method = method, over = F) 

  } else {

    roi_ranking_projected <- local_raster %>%
      projectRaster(crs = crs('+proj=eqearth +lon_0=0 +wktext'),
                    method = method, over = F) 

  }
  return(roi_ranking_projected)
}

```

```{r}
make_national_maps <- function(global_ranking_raster, 
                               global_mpas_raster, 
                               global_mpas_polys, 
                               iso_codes, 
                               land_polys, 
                               global_breaks,
                               global_eez_polys,
                               global_eez_polys_with_land,
                               goal){

  local_ranking <- global_ranking_raster %>% 
    subset_priorities_raster(iso_codes, eez_file = global_eez_polys_with_land)
  
  local_mpas <- mpas_raster %>%  
    subset_priorities_raster(iso_codes, eez_file = global_eez_polys_with_land)

  fraction_in_MPAs <- cellStats(local_mpas, function(x, ...) sum(!is.na(x)))/cellStats(local_ranking, function(x, ...) sum(!is.na(x)))
  
  local_ranking <- local_ranking %>% 
    reproject_local_raster(method = "bilinear")
  
  world_data <- rnaturalearth::ne_countries(scale = 50, returnclass = "sf")
  
  local_land <- world_data %>%
      filter_all(., any_vars(str_detect(., iso_codes))) %>% 
      st_transform(crs(local_ranking)) 
  
  local_land_raster <- local_land %>% 
    rasterize(local_ranking, getCover = T)

  local_land_raster[local_land_raster < 1] <- NA
  
  local_ranking <- local_ranking %>% 
    mask(local_land_raster, inverse = T) 

  local_mpas <- local_mpas %>% 
    projectRaster(local_ranking, method = "ngb") %>% 
    extend(local_ranking)

  extent(local_mpas) <- alignExtent(extent = extent(local_mpas), 
                                    local_ranking, snap = "near")
  
  if(fraction_in_MPAs > 0 & !is.na(fraction_in_MPAs)){
    
    local_ranking <- overlay(local_ranking, 
                             local_mpas,
                             fun = function(x, y){ifelse(!is.na(y), 1, x)}) %>% 
      mask(local_ranking)
    }
  
  
  local_ranking_df <- local_ranking %>% 
    as.data.frame(xy = T) %>% 
    set_names(c("lon", "lat", "global_rank")) %>% 
    arrange(desc(global_rank)) %>% 
    filter(!is.na(global_rank)) %>% 
    mutate(is_mpa = if_else(global_rank == 1, 1, 0),
           national_rank = rank(global_rank, ties.method = "last"),
           f = 1/n(), 
           national_rank = 1 - cumsum(f)) %>%
    select(-f) 

  # local_land <- local_land %>% 
  #   st_crop(trim(local_ranking))

  local_eez <- global_eez_polys %>% 
    filter(iso_ter1 %in% iso_codes) %>% 
    st_union() %>% 
    st_set_crs(st_crs(global_eez_polys)) %>% 
    st_transform(crs = crs(local_ranking))
  
  if(fraction_in_MPAs > 0 & !is.na(fraction_in_MPAs)){
    
    local_mpas_sf <- global_mpas_polys %>% 
      filter(country %in% iso_codes) %>% 
      lwgeom::st_make_valid() %>% 
      st_transform(st_crs(local_eez)) %>% 
      st_crop(local_eez) %>% 
      st_simplify(preserveTopology = T, dTolerance = 0.01)
    }
  
  min_local_rank_in_mpa <- min(1, min(local_ranking_df$national_rank[local_ranking_df$global_rank == 1]))
  
  local_breaks <- sort(unique(c(global_breaks, min_local_rank_in_mpa)))
  
  local_labels <- local_breaks[-1]
  
  local_colors <- global_cols
  
  local_colors[local_labels > min_local_rank_in_mpa] <- "#47A025"
  
  local_labels <- 100 - 100*local_labels
  
  local_labels[local_labels ==  (100-100*min_local_rank_in_mpa)] <- " "
  
  local_legend_key_widths <- tibble(to = as.numeric(as.character(local_breaks[-1])),
                                    from = lag(to)) %>% 
    replace_na(list(from = 0)) %>%
    mutate(range = to - from) %>% 
    mutate(w = range*0.6) %>% 
    mutate(w2 = if_else(to <= 0.8, w/1.5, w))
  
  local_map <- local_ranking_df %>% 
    mutate(rank_cut = cut(national_rank, 
                          breaks = local_breaks,
                          labels = local_breaks[-1],
                          include.lowest = T)) %>% 
    replace_na(list(rank_cut = 1)) %>%
    ggplot(aes(x = lon, y = lat))+
    geom_raster(aes(fill = rank_cut), alpha = 1)+
    geom_sf(data = local_land, inherit.aes = F, size = 0.5)+
    #geom_sf(data = local_eez, inherit.aes = F, fill = "transparent", linetype = 2, size = 0.5)+
    scale_fill_manual(na.value="black", 
                      values  = local_colors,
                      labels = local_labels,
                      guide = guide_legend(title = "Top % of EEZ",
                                           direction = "horizontal",
                                           keyheight = unit(0.01, "npc"),
                                           keywidth = unit(rev(local_legend_key_widths$w2), "npc"),
                                           title.position = 'top',
                                           title.hjust = 0.5,
                                           label.hjust = -.02,
                                           nrow = 1,
                                           byrow = T,
                                           reverse = T,
                                           label.position = "bottom"))+
    labs(title = "National Conservation Priorities",
         subtitle = goal,
         caption = "Existing highly protected areas shown in green.")+
    theme_maps
  
  if(fraction_in_MPAs > 0 & !is.na(fraction_in_MPAs)){
    
    local_map <- local_map + 
      geom_sf(data = local_mpas_sf, inherit.aes = F, fill = "#47A025", col = "transparent")}

    ggsave(plot = local_map, 
           filename = file.path(emLab_project_dir, "figures", "national_maps", "commonwealth_no_eez", paste0(paste(iso_codes, goal, sep = "_"), ".png")))
}
```

```{r}
commowealth_countries <- c("Botswana","Cameroon","Gambia","Ghana","Kenya","Lesotho","Malawi","Mauritius","Mozambique","Namibia","Nigeria","Rwanda","Seychelles","Sierra Leone","South Africa","Uganda","United Republic of Tanzania","Zambia","Bangladesh","Brunei Darussalam","India","Malaysia","Maldives","Pakistan","Singapore","Sri Lanka","Antigua and Barbuda","Bahamas","Barbados","Belize","Canada","Dominica","Grenada","Guyana","Jamaica","Saint Lucia","St Kitts and Nevis","St Vincent and The Grenadines","Trinidad and Tobago","Cyprus","Malta","United Kingdom","Australia","Fiji","Kiribati","Nauru","New Zealand","Papua New Guinea","Samoa","Solomon Islands","Tonga","Tuvalu","Vanuatu")

commonealth_isos <- countrycode::countrycode(commowealth_countries, origin = "country.name", destination = "iso3c")

tmp_isos <- commonealth_isos[!commonealth_isos %in% sub("_[^_]+$", "", list.files(file.path(emLab_project_dir, "figures", "national_maps", "commonwealth_no_eez")))]
```

```{r}
results <- expand_grid(iso_codes = "TUV",
                       ranking = c(food_ranking, carbon_ranking, bio_ranking)) %>% 
  mutate(goal = rep(c("Food", "Carbon", "Biodiversity"), 1),
         map = purrr::pwalk(.l = list(iso_codes = iso_codes, goal = goal, global_ranking_raster = ranking),
                            .f = make_national_maps,
                            global_mpas_raster = mpas_raster, 
                            global_mpas_polys = mpas_polys, 
                            land_polys = land_50, 
                            global_breaks = global_breaks,
                            global_eez_polys  = eez,
                            global_eez_polys_with_land = eez_with_land))
```

# Exceptions to the norm

## TUV

```{r}
TUV_make_national_maps <- function(global_ranking_raster, 
                               global_mpas_raster, 
                               global_mpas_polys, 
                               iso_codes, 
                               land_polys, 
                               global_breaks,
                               global_eez_polys,
                               global_eez_polys_with_land,
                               goal){

  local_ranking <- global_ranking_raster %>% 
    subset_priorities_raster(iso_codes, eez_file = global_eez_polys_with_land)
  
  local_mpas <- mpas_raster %>%  
    subset_priorities_raster(iso_codes, eez_file = global_eez_polys_with_land)

  fraction_in_MPAs <- cellStats(local_mpas, function(x, ...) sum(!is.na(x)))/cellStats(local_ranking, function(x, ...) sum(!is.na(x)))
  
  local_ranking <- local_ranking %>% 
    reproject_local_raster(method = "bilinear")
  

  local_mpas <- local_mpas %>% 
    projectRaster(local_ranking, method = "ngb") %>% 
    extend(local_ranking)

  extent(local_mpas) <- alignExtent(extent = extent(local_mpas), 
                                    local_ranking, snap = "near")
  
  if(fraction_in_MPAs > 0 & !is.na(fraction_in_MPAs)){
    
    local_ranking <- overlay(local_ranking, 
                             local_mpas,
                             fun = function(x, y){ifelse(!is.na(y), 1, x)}) %>% 
      mask(local_ranking)
    }
  
  
  local_ranking_df <- local_ranking %>% 
    as.data.frame(xy = T) %>% 
    set_names(c("lon", "lat", "global_rank")) %>% 
    arrange(desc(global_rank)) %>% 
    filter(!is.na(global_rank)) %>% 
    mutate(is_mpa = if_else(global_rank == 1, 1, 0),
           national_rank = rank(global_rank, ties.method = "last"),
           f = 1/n(), 
           national_rank = 1 - cumsum(f)) %>%
    select(-f) 

  # local_land <- local_land %>% 
  #   st_crop(trim(local_ranking))

  local_eez <- global_eez_polys %>% 
    filter(iso_ter1 %in% iso_codes) %>% 
    st_union() %>% 
    st_set_crs(st_crs(global_eez_polys)) %>% 
    st_transform(crs = crs(local_ranking))
  
  if(fraction_in_MPAs > 0 & !is.na(fraction_in_MPAs)){
    
    local_mpas_sf <- global_mpas_polys %>% 
      filter(country %in% iso_codes) %>% 
      lwgeom::st_make_valid() %>% 
      st_transform(st_crs(local_eez)) %>% 
      st_crop(local_eez) %>% 
      st_simplify(preserveTopology = T, dTolerance = 0.01)
    }
  
  min_local_rank_in_mpa <- min(1, min(local_ranking_df$national_rank[local_ranking_df$global_rank == 1]))
  
  local_breaks <- sort(unique(c(global_breaks, min_local_rank_in_mpa)))
  
  local_labels <- local_breaks[-1]
  
  local_colors <- global_cols
  
  local_colors[local_labels > min_local_rank_in_mpa] <- "#47A025"
  
  local_labels <- 100 - 100*local_labels
  
  local_labels[local_labels ==  (100-100*min_local_rank_in_mpa)] <- " "
  
  local_legend_key_widths <- tibble(to = as.numeric(as.character(local_breaks[-1])),
                                    from = lag(to)) %>% 
    replace_na(list(from = 0)) %>%
    mutate(range = to - from) %>% 
    mutate(w = range*0.6) %>% 
    mutate(w2 = if_else(to <= 0.8, w/1.5, w))
  
  local_map <- local_ranking_df %>% 
    mutate(rank_cut = cut(national_rank, 
                          breaks = local_breaks,
                          labels = local_breaks[-1],
                          include.lowest = T)) %>% 
    replace_na(list(rank_cut = 1)) %>%
    ggplot(aes(x = lon, y = lat))+
    geom_raster(aes(fill = rank_cut), alpha = 1)+
    #geom_sf(data = local_eez, inherit.aes = F, fill = "transparent", linetype = 2, size = 0.5)+
    scale_fill_manual(na.value="black", 
                      values  = local_colors,
                      labels = local_labels,
                      guide = guide_legend(title = "Top % of EEZ",
                                           direction = "horizontal",
                                           keyheight = unit(0.01, "npc"),
                                           keywidth = unit(rev(local_legend_key_widths$w2), "npc"),
                                           title.position = 'top',
                                           title.hjust = 0.5,
                                           label.hjust = -.02,
                                           nrow = 1,
                                           byrow = T,
                                           reverse = T,
                                           label.position = "bottom"))+
    labs(title = "National Conservation Priorities",
         subtitle = goal,
         caption = "Existing highly protected areas shown in green. Dashed line corresponds to EEZ limits.")+
    theme_maps
  
  if(fraction_in_MPAs > 0 & !is.na(fraction_in_MPAs)){
    
    local_map <- local_map + 
      geom_sf(data = local_mpas_sf, inherit.aes = F, fill = "#47A025", col = "transparent")}

    ggsave(plot = local_map, 
           filename = file.path(emLab_project_dir, "figures", "national_maps", "commonwealth_no_eez", paste0(paste(iso_codes, goal, sep = "_"), ".png")))
}

results <- expand_grid(iso_codes = "TUV",
                       ranking = c(food_ranking, carbon_ranking, bio_ranking)) %>% 
  mutate(goal = rep(c("Food", "Carbon", "Biodiversity"), 1),
         map = purrr::pwalk(.l = list(iso_codes = iso_codes, goal = goal, global_ranking_raster = ranking),
                            .f = TUV_make_national_maps,
                            global_mpas_raster = mpas_raster, 
                            global_mpas_polys = mpas_polys, 
                            land_polys = land_50, 
                            global_breaks = global_breaks,
                            global_eez_polys  = eez,
                            global_eez_polys_with_land = eez_with_land))
```

