---
title: "Figure 7: Propeller plot"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
library(raster)
library(sf)
library(tidyverse)
library(patchwork)
extrafont::loadfonts()
source(here::here("common.R"))

circle_theme <- theme(axis.line=element_blank(),
                      axis.text.y=element_blank(),
                      axis.ticks=element_blank(),
                      axis.title.x=element_blank(),
                      axis.title.y=element_blank(),
                      legend.position="none",
                      panel.background=element_blank(),
                      panel.border=element_blank(),
                      panel.grid.major=element_blank(),
                      panel.grid.minor=element_blank(),
                      plot.background=element_blank(),
                      axis.text.x = element_blank())

theme_map <- function(...) {
  theme_minimal() +
    theme(
      axis.line = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = NA, color = NA), 
      panel.background = element_rect(fill = NA, color = NA), 
      legend.background = element_rect(fill = NA, color = NA),
      panel.border = element_blank(),
      ...
    )
}
```

```{r}
MPAs <- raster(file.path(emLab_project_dir, "data", "02_processed", "masks", "fully_highly_protected_reviewed_MPAs.tif"))

MPAs_df <- MPAs %>% 
  raster::as.data.frame(xy = T) %>%
  inner_join(ocean_matrix) %>% 
  select(x, y, cell_id, mpa = fully_highly_protected_reviewed_MPAs) %>%
  as_tibble() 

fraction_in_MPA <- sum(!is.na(MPAs_df$mpa))/nrow(MPAs_df)

n_ocean_cells <- cellStats(ocean_low_res_moll, function(x, ...) sum(!is.na(x)))

(n_cells_MPAs <- MPAs %>% cellStats(function(x, ...) sum(!is.na(x))))
  
(global_percent_protected <- 100*n_cells_MPAs/n_ocean_cells)

eez_shp <- sf::st_read(file.path(emLab_shrd_data_dir, "marine-regions-EEZ-land-union-v3-202003", "EEZ_Land_v3_202030.shp")) %>% 
  sf::st_wrap_dateline(options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"), quiet = TRUE) %>% 
  sf::st_transform(crs(ocean_low_res_moll)) %>% 
  sf::st_simplify(dTolerance = 0) %>% 
  janitor::clean_names()

eez_info <- eez_shp %>% 
  st_drop_geometry() 
  
eez_info <- eez_info %>% 
  mutate_if(is.factor, as.character) %>% 
  rename(name = union) %>% 
  mutate(iso_ter1 = case_when(
  name %in% c("Alaska", "Hawaii") ~ "USA",
  name %in% c("Kuril Islands") ~ "RUS",
  name %in% c("Azores", "Madeira") ~ "PRT",
  name %in% c("Canary Islands", "Chafarinas Islands", "Ceuta", "Melilla", "Peñón de Vélez de la Gomera","Perejil Island", "Alhucemas Islands") ~ "ESP",
  name %in% c("Senkaku Islands", "Overlapping claim Liancourt Rocks: Japan / South Korea") ~ "JPN",
  name %in% c("Navassa Island") ~ "JAM",
  name %in% c("Serranilla Bank", "Colombian Exclusive Economic Zone (Quitasueño)", "Bajo Nuevo Bank", "Serrana Bank") ~ "COL",
  name %in% c("Andaman and Nicobar") ~ "IND",
  name %in% c("Clipperton Island") ~ "CLI",
  name %in% c("Galapagos") ~ "ECU",
  name %in% c("Chagos Archipelago") ~ "CHG",
  name %in% c("Oecusse") ~ "TLS",
  name %in% c("Glorioso Islands", "Tromelin Island") ~ "ATF",
  name %in% c("Trinidade") ~ "BRA",
  name %in% c("Matthew and Hunter Islands") ~ "NCL",
  name %in% c("Easter Island") ~ "CHL",
  name %in% c("Prince Edward Islands") ~ "ZAF",
  name %in% c("Macquarie Island") ~ "AUS", 
  name %in% c("Doumeira Islands") ~ "ERI", 
  TRUE ~ iso_ter1
  )) 

```

# Biodiversity

```{r}
biodiversity_priorities_raster <- raster(file.path(emLab_project_dir, "data", "03_output", "05_spp_wts_smts_provs_MPAs", "ranking_raster.tif"))

delta_bio_V_raster <- raster(file.path(emLab_project_dir, "data", "03_output", "05_spp_wts_smts_provs_MPAs", "delta_v_raster.tif"))

n_ocean_cells_top_5 <- cellStats(biodiversity_priorities_raster, function(x, ...) sum(x >= 0.95, na.rm = T))
n_ocean_cells_top_10 <- cellStats(biodiversity_priorities_raster, function(x, ...) sum(x >= 0.9, na.rm = T))
n_ocean_cells_top_20 <- cellStats(biodiversity_priorities_raster, function(x, ...) sum(x >= 0.8, na.rm = T))
n_ocean_cells_top_30 <- cellStats(biodiversity_priorities_raster, function(x, ...) sum(x >= 0.7, na.rm = T))

bio_stats_by_country <- biodiversity_priorities_raster %>% 
  mask(MPAs, updatevalue = 100, inverse = T) %>% 
  raster::extract(eez_shp, df = T) %>% 
  select(ID, cell_rank = 2) %>% 
  group_by(ID) %>% 
  summarize(n_cells = sum(cell_rank >= 0, na.rm = T),
            n_protected_cells = sum(cell_rank >= 100, na.rm = T),
            n_cells_top_20 = sum(cell_rank >= .80, na.rm = T),
            n_cells_top_10 = sum(cell_rank >= .90, na.rm = T),
            n_cells_top_5 = sum(cell_rank >= .95, na.rm = T)) %>% 
  ungroup() %>% 
  filter(n_cells > 0) %>% 
  left_join(eez_info %>% 
              rowid_to_column() %>% 
              select(ID = rowid, iso3 =  iso_ter1, iso3_sov = iso_sov1, mrgid_ter1, mrgid_eez, name)) %>% 
  select(mrgid_ter1, iso3, iso3_sov, mrgid_eez, everything(), -ID) %>% 
  mutate(goal = "biodiversity") 

bio_contribution_to_top_10 <- delta_bio_V_raster %>% 
  mask(MPAs, inverse = T) %>% 
  mask(biodiversity_priorities_raster >= 0.9, maskvalue = 0) %>% 
  raster::extract(eez_shp, df = T) %>% 
  select(ID, dV = 2) %>% 
  group_by(ID) %>% 
  summarize(sum_dV = sum(dV, na.rm = T)) %>% 
  left_join(eez_info %>% 
              rowid_to_column() %>% 
              select(ID = rowid, iso3 =  iso_ter1, iso3_sov = iso_sov1, mrgid_ter1, mrgid_eez)) %>% 
  select(mrgid_ter1, iso3, iso3_sov, mrgid_eez, everything(), -ID)

bio_stats_by_country <- bio_stats_by_country %>% 
  left_join(bio_contribution_to_top_10) %>% 
  rename(sum_delta_v_10_percent = sum_dV)
```

# Carbon

```{r}
carbon_priorities_raster <- raster(file.path(emLab_project_dir, "data", "03_output", "06_carbon", "ranking_raster.tif"))
delta_carbon_V_raster <- raster(file.path(emLab_project_dir, "data", "03_output", "06_carbon", "delta_v_raster.tif"))

carbon_stats_by_country <- carbon_priorities_raster %>% 
  mask(MPAs, updatevalue = 100, inverse = T) %>% 
  raster::extract(eez_shp, df = T) %>% 
  select(ID, cell_rank = 2) %>% 
  group_by(ID) %>% 
  summarize(n_cells = sum(cell_rank >= 0, na.rm = T),
            n_protected_cells = sum(cell_rank >= 100, na.rm = T),
            n_cells_top_20 = sum(cell_rank >= .80, na.rm = T),
            n_cells_top_10 = sum(cell_rank >= .90, na.rm = T),
            n_cells_top_5 = sum(cell_rank >= .95, na.rm = T)) %>% 
  ungroup() %>% 
  filter(n_cells > 0) %>% 
  left_join(eez_info %>% 
              rowid_to_column() %>% 
              select(ID = rowid, iso3 =  iso_ter1, iso3_sov = iso_sov1, mrgid_ter1, mrgid_eez, name)) %>% 
  select(mrgid_ter1, iso3, iso3_sov, mrgid_eez, everything(), -ID) %>% 
  mutate(goal = "carbon") 

carbon_contribution_to_top_10 <- delta_carbon_V_raster %>% 
  mask(MPAs, inverse = T) %>% 
  mask(carbon_priorities_raster >= 0.9, maskvalue = 0) %>% 
  raster::extract(eez_shp, df = T) %>% 
  select(ID, dV = 2) %>% 
  group_by(ID) %>% 
  summarize(sum_dV = sum(dV, na.rm = T)) %>% 
  left_join(eez_info %>% 
              rowid_to_column() %>% 
              select(ID = rowid, iso3 =  iso_ter1, iso3_sov = iso_sov1, mrgid_ter1, mrgid_eez)) %>% 
  select(mrgid_ter1, iso3, iso3_sov, mrgid_eez, everything(), -ID)

carbon_stats_by_country <- carbon_stats_by_country %>% 
  left_join(carbon_contribution_to_top_10) %>% 
  rename(sum_delta_v_10_percent = sum_dV)
```

# Food

```{r}
food_priorities_raster <- raster(file.path(emLab_project_dir, "data", "03_output", "07_food", "ranking_raster.tif"))
delta_food_V_raster <- raster(file.path(emLab_project_dir, "data", "03_output", "07_food", "delta_v_raster.tif"))

food_stats_by_country <- food_priorities_raster %>% 
  mask(MPAs, updatevalue = 100, inverse = T) %>% 
  raster::extract(eez_shp, df = T) %>% 
  select(ID, cell_rank = 2) %>% 
  group_by(ID) %>% 
  summarize(n_cells = sum(cell_rank >= 0, na.rm = T),
            n_protected_cells = sum(cell_rank >= 100, na.rm = T),
            n_cells_top_20 = sum(cell_rank >= .80, na.rm = T),
            n_cells_top_10 = sum(cell_rank >= .90, na.rm = T),
            n_cells_top_5 = sum(cell_rank >= .95, na.rm = T)) %>% 
  ungroup() %>% 
  filter(n_cells > 0) %>% 
  left_join(eez_info %>% 
              rowid_to_column() %>% 
              select(ID = rowid, iso3 =  iso_ter1, iso3_sov = iso_sov1, mrgid_ter1, mrgid_eez, name)) %>% 
  select(mrgid_ter1, iso3, iso3_sov, mrgid_eez, everything(), -ID) %>% 
  mutate(goal = "food") 

food_contribution_to_top_10 <- delta_food_V_raster %>% 
  mask(MPAs, inverse = T) %>% 
  mask(food_priorities_raster >= 0.9, maskvalue = 0) %>% 
  raster::extract(eez_shp, df = T) %>% 
  select(ID, dV = 2) %>% 
  group_by(ID) %>% 
  summarize(sum_dV = sum(dV, na.rm = T)) %>% 
  left_join(eez_info %>% 
              rowid_to_column() %>% 
              select(ID = rowid, iso3 =  iso_ter1, iso3_sov = iso_sov1, mrgid_ter1, mrgid_eez)) %>% 
  select(mrgid_ter1, iso3, iso3_sov, mrgid_eez, everything(), -ID)

food_stats_by_country <- food_stats_by_country %>% 
  left_join(food_contribution_to_top_10) %>% 
  rename(sum_delta_v_10_percent = sum_dV)
```

# Combined goals and clean country names

```{r}
stats_by_country <- bind_rows(bio_stats_by_country, 
                              carbon_stats_by_country,
                              food_stats_by_country) %>% 
  mutate(continent = countrycode::countrycode(iso3, "iso3c", "continent")) %>% 
  group_by(iso3, goal, continent) %>% 
  summarize_at(vars(n_cells, n_protected_cells, n_cells_top_5, n_cells_top_10, n_cells_top_20, sum_delta_v_10_percent), sum) %>% 
  mutate(fraction_protected = n_protected_cells/n_cells,
         fraction_top_5 = n_cells_top_5/n_cells,
         fraction_top_10 = n_cells_top_10/n_cells,
         fraction_top_20 = n_cells_top_20/n_cells,
         contribution_top_5 = n_cells_top_5/n_ocean_cells_top_5,
         contribution_top_10 = n_cells_top_5/n_ocean_cells_top_10,
         contribution_top_20 = n_cells_top_5/n_ocean_cells_top_20) %>% 
  filter(iso3 != "VAT")
```

```{r}
## Combine goals ----

stats_by_country <- stats_by_country %>% 
  mutate(continent = case_when(
    iso3 == "ATF" ~ "Southern\nIslands",
    iso3 == "SGS" ~ "Southern\nIslands",
    iso3 == "HMD" ~ "Southern\nIslands",
    iso3 == "ATA" ~ "Southern\nIslands",
    iso3 == "CHG" ~ "Asia",
    iso3 == "TAA" ~ "Europe",
    iso3 == "ASC" ~ "Europe",
    iso3 == "BVT" ~ "Southern\nIslands",
    iso3 == "UMI" ~ "Oceania",
    iso3 == "CCK" ~ "Oceania",
    iso3 == "IOT" ~ "Europe",
    iso3 == "MNP++" ~ "Oceania",
    iso3 == "CW" ~ "Americas",
    iso3 == "ANT" ~ "Americas",
    iso3 == "CLI" ~ "Americas",
    TRUE ~ continent
  )) 

stats_by_country <- stats_by_country %>% 
  mutate(country = countrycode::countrycode(sourcevar =  iso3, origin = "iso3c", destination = "country.name")) 

stats_by_country$country[stats_by_country$iso3 == "CLI"] <- "Clipperton Isl"

stats_by_country$country[stats_by_country$iso3 == "CHG"] <- "Chagos"

stats_by_country <- stats_by_country %>%
  mutate(country = gsub("Islands", "Isl", country),
         country = gsub("Island", "Isl", country),
         country = gsub("Democratic", "Dem", country),
         country = gsub("Republic", "Rep", country),
         country = gsub("South", "S", country),
         country = gsub("American", "Am", country),
         country = gsub("the United States", "US", country),
         country = gsub("country", "Terr", country),
         country = gsub("Saint", "St", country),
         country = gsub(" and ", " & ", country),
         country = gsub("Republique", "Rep", country),
         country = gsub("Dem Rep of the", "Dem Rep of", country),
         country = gsub("Georgia and the", "Georgia and", country),
         country = gsub("St Vincent and the", "St Vincent and", country),
         country = gsub("Howland Isl & Baker Isl", "Howland & Baker Isl", country),
         country = gsub("Northern", "N", country), 
         country = gsub("Reunion", "Reunion   ", country))

stats_by_country$country[stats_by_country$iso3 == "ATF"] <- "ATF"

stats_by_country$country[stats_by_country$iso3 == "UMI"] <- "U.S Minor Outlying Isl"

stats_by_country$country[stats_by_country$iso3 == "MNP++"] <- "MNP++"

stats_by_country$country[stats_by_country$iso3 == "SGS"] <- "SGS"

stats_by_country$country[stats_by_country$iso3 == "VIR"] <- "U.S Virgin Isl"

stats_by_country$country[stats_by_country$iso3 == "SHN"] <- "SHN"

stats_by_country$country[stats_by_country$iso3 == "GBR"] <- "GBR"

stats_by_country$country[stats_by_country$iso3 == "UMI"] <- "UMI"

stats_by_country$country[stats_by_country$iso3 == "PNG"] <- "PNG"

stats_by_country$country[stats_by_country$iso3 == "DOM"] <- "DOM"

stats_by_country$country[stats_by_country$iso3 == "HMD"] <- "HMD"
```

# Most important countries 

```{r}
# bio_top_countries <- stats_by_country %>% 
#   filter(goal == "biodiversity") %>% 
#   top_n(100, wt = (n_cells_top_20 - n_protected_cells)/n_ocean_cells_top_20) %>% 
#   pull(country)

bio_top_countries <- stats_by_country %>% 
  filter(goal == "biodiversity") %>% 
  ungroup() %>% 
  top_n(100, sum_delta_v_10_percent) %>% 
  pull(country)

# carbon_top_countries <- stats_by_country %>% 
#   filter(goal == "carbon") %>% 
#   top_n(100, wt = (n_cells_top_20 - n_protected_cells)/n_ocean_cells_top_20) %>% 
#   pull(country)

carbon_top_countries <-stats_by_country %>% 
  filter(goal == "carbon") %>% 
  ungroup() %>% 
  top_n(100, wt = sum_delta_v_10_percent) %>% 
  pull(country)

# food_top_countries <- stats_by_country %>% 
#   filter(goal == "food") %>% 
#   top_n(100, wt = (n_cells_top_20 - n_protected_cells)/n_ocean_cells_top_20) %>% 
#   pull(country)

food_top_countries <- stats_by_country %>% 
  filter(goal == "food") %>% 
  ungroup() %>% 
  arrange(desc(sum_delta_v_10_percent)) %>% 
  head(100) %>%
  pull(country)
```

# Make plots

## Biodiversity

```{r}
plotting_data <- stats_by_country %>% 
  filter(country %in% bio_top_countries, goal == "biodiversity" ) %>% 
  ungroup() %>% 
  mutate(continent = factor(continent),
         value = fraction_top_10 - fraction_protected) %>% 
  select(country, continent, goal, value) %>% 
  arrange(continent, value)

plotting_data <- plotting_data %>% 
  add_row(continent = rep(unique(plotting_data$continent), 3)) %>% 
  arrange(continent) %>% 
  rowid_to_column("id")

label_data <- plotting_data %>%  
  mutate(angle = 90 - 360 * (id - 0.5) /nrow(plotting_data)) %>% # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
  mutate(hjust = ifelse(angle < -90, 1, 0),
         angle = ifelse(angle < -90, angle+180, angle))

# prepare a data frame for base lines
base_data <- plotting_data %>% 
  group_by(continent) %>% 
  summarize(start = min(id), 
            end = max(id) - 3) %>% 
  rowwise() %>% 
  mutate(title = mean(c(start, end))) %>% 
  ungroup()

#base_data$hjust <- c(1, 0.7, 0 , 0, 0.4, 0.5)

# prepare a data frame for grid (scales)
grid_data <- base_data %>%
  mutate(end = data.table::shift(end + 1, n = 1, type = "shift", fill = max(end) + 1),
         start = start -1) %>% 
  slice(-1)

max_value <- 100*max(plotting_data$value, na.rm = T)

y_max <- 20 * ceiling(max_value/20)

#v <- seq(20, y_max, by = 20)
v <- c(20,40,60,80,100)

grid_data <- grid_data %>% 
  mutate(v = list(v)) %>% 
  unnest()

propeller_bio_plot <- plotting_data %>% 
  ggplot(aes(x = as.factor(id), y = 100*value, fill = continent))+
  geom_col(width = 0.8) +
  geom_segment(data = grid_data, 
               aes(x = end, y = v, xend = start, yend = v), colour = "grey", size=0.3 , inherit.aes = FALSE ) +
  annotate("text", 
           x = rep(max(plotting_data$id), length(v)), 
           y = v , label = paste0(head(v), "%"), color = "grey", size = 4 , angle = 0, fontface = "bold", hjust = 0.7)+
  ylim(-40, y_max)+ 
  theme_minimal() +
  coord_polar()+
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(0,4), "cm")
  )+
  geom_text(data = label_data, 
            aes(x = id, y = y_max, label = country, hjust = hjust), 
            color="black",  size = 4, angle = label_data$angle, inherit.aes = FALSE)+
  geom_text(data = base_data, 
            aes(x = title, y = 35, label = continent),  colour = "black", alpha = 0.8, size = 4, fontface = "bold", inherit.aes = FALSE) +
  theme_map()+
  circle_theme 

ggsave(propeller_bio_plot, 
       filename = file.path(emLab_project_dir, "figures", "supplement" ,"propeller_bio.png"), 
       dpi = 300,  height = 13, width = 13)
```

## Carbon

```{r}
plotting_data <- stats_by_country %>% 
  filter(country %in% carbon_top_countries, goal == "carbon" ) %>% 
  ungroup() %>% 
  mutate(continent = factor(continent),
         value = fraction_top_10 - fraction_protected) %>% 
  select(country, continent, goal, value) %>% 
  arrange(continent, value)

plotting_data <- plotting_data %>% 
  add_row(continent = rep(unique(plotting_data$continent), 3)) %>% 
  arrange(continent) %>% 
  rowid_to_column("id")

label_data <- plotting_data %>%  
  mutate(angle = 90 - 360 * (id - 0.5) /nrow(plotting_data)) %>% # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
  mutate(hjust = ifelse(angle < -90, 1, 0),
         angle = ifelse(angle < -90, angle+180, angle))

# prepare a data frame for base lines
base_data <- plotting_data %>% 
  group_by(continent) %>% 
  summarize(start = min(id), 
            end = max(id) - 3) %>% 
  rowwise() %>% 
  mutate(title = mean(c(start, end))) %>% 
  ungroup()

#base_data$hjust <- c(1, 0.7, 0 , 0, 0.4, 0.5)

# prepare a data frame for grid (scales)
grid_data <- base_data %>%
  mutate(end = data.table::shift(end + 1, n = 1, type = "shift", fill = max(end) + 1),
         start = start -1) %>% 
  slice(-1)

max_value <- 100*max(plotting_data$value, na.rm = T)

y_max <- 20 * ceiling(max_value/20)

#v <- seq(20, y_max, by = 20)
v <- c(20,40,60,80,100)

grid_data <- grid_data %>% 
  mutate(v = list(v)) %>% 
  unnest()

propeller_carbon_plot <- plotting_data %>% 
  ggplot(aes(x = as.factor(id), y = 100*value, fill = continent))+
  geom_col(width = 0.8) +
  geom_segment(data = grid_data, 
               aes(x = end, y = v, xend = start, yend = v), colour = "grey", size=0.3 , inherit.aes = FALSE ) +
  annotate("text", 
           x = rep(max(plotting_data$id), length(v)), 
           y = v , label = paste0(head(v), "%"), color = "grey", size = 4 , angle = 0, fontface = "bold", hjust = 0.7)+
  ylim(-40, y_max)+ 
  theme_minimal() +
  coord_polar()+
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(0,4), "cm")
  )+
  geom_text(data = label_data, 
            aes(x = id, y = y_max, label = country, hjust = hjust), 
            color="black",  size = 4, angle = label_data$angle, inherit.aes = FALSE)+
  geom_text(data = base_data, 
            aes(x = title, y = 35, label = continent),  colour = "black", alpha = 0.8, size = 4, fontface = "bold", inherit.aes = FALSE) +
  theme_map()+
  circle_theme 

ggsave(propeller_carbon_plot, 
       filename = file.path(emLab_project_dir, "figures", "supplement" ,"propeller_carbon.png"), 
       dpi = 300,  height = 10, width = 10)
```

## Food

```{r}
plotting_data <- stats_by_country %>% 
  filter(country %in% food_top_countries, goal == "food" ) %>% 
  ungroup() %>% 
  mutate(continent = factor(continent),
         value = fraction_top_10 - fraction_protected) %>% 
  select(country, continent, goal, value) %>% 
  arrange(continent, value)

plotting_data <- plotting_data %>% 
  add_row(continent = rep(unique(plotting_data$continent), 3)) %>% 
  arrange(continent) %>% 
  rowid_to_column("id")

label_data <- plotting_data %>%  
  mutate(angle = 90 - 360 * (id - 0.5) /nrow(plotting_data)) %>% # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
  mutate(hjust = ifelse(angle < -90, 1, 0),
         angle = ifelse(angle < -90, angle+180, angle))

# prepare a data frame for base lines
base_data <- plotting_data %>% 
  group_by(continent) %>% 
  summarize(start = min(id), 
            end = max(id) - 3) %>% 
  rowwise() %>% 
  mutate(title = mean(c(start, end))) %>% 
  ungroup()

#base_data$hjust <- c(1, 0.7, 0 , 0, 0.4, 0.5)

# prepare a data frame for grid (scales)
grid_data <- base_data %>%
  mutate(end = data.table::shift(end + 1, n = 1, type = "shift", fill = max(end) + 1),
         start = start -1) %>% 
  slice(-1)

max_value <- 100*max(plotting_data$value, na.rm = T)

y_max <- 20 * ceiling(max_value/20)

#v <- seq(20, y_max, by = 20)
v <- c(20,40,60,80,100)

grid_data <- grid_data %>% 
  mutate(v = list(v)) %>% 
  unnest()

propeller_food_plot <- plotting_data %>% 
  ggplot(aes(x = as.factor(id), y = 100*value, fill = continent))+
  geom_col(width = 0.8) +
  geom_segment(data = grid_data, 
               aes(x = end, y = v, xend = start, yend = v), colour = "grey", size=0.3 , inherit.aes = FALSE ) +
  annotate("text", 
           x = rep(max(plotting_data$id), length(v)), 
           y = v , label = paste0(head(v), "%"), color = "grey", size = 4 , angle = 0, fontface = "bold", hjust = 0.7)+
  ylim(-40, y_max)+ 
  theme_minimal() +
  coord_polar()+
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(0,4), "cm")
  )+
  geom_text(data = label_data, 
            aes(x = id, y = y_max, label = country, hjust = hjust), 
            color="black",  size = 4, angle = label_data$angle, inherit.aes = FALSE)+
  geom_text(data = base_data, 
            aes(x = title, y = 35, label = continent),  colour = "black", alpha = 0.8, size = 4, fontface = "bold", inherit.aes = FALSE) +
  theme_map()+
  circle_theme 

ggsave(propeller_food_plot, 
       filename = file.path(emLab_project_dir, "figures", "supplement" ,"propeller_food.png"), 
       dpi = 300,  height = 10, width = 10)
```

# Efficiency loss

```{r}
bio_benefit_curves <- read_rds(file.path(emLab_project_dir, "data", "03_output", "05_spp_wts_smts_provs_MPAs", "benefit_curves.rds")) %>% 
  mutate(cell_id = as.character(cell_id))

spp_wts <- data.table::fread(file.path(emLab_project_dir, "data", "02_processed", "species_list", "spp_weights.csv")) %>% 
  as_tibble() %>% 
  rename(w = spp_weight)

smts_wts <- tibble(filepath = list.files(file.path(emLab_project_dir, "data", "02_processed","seamounts"), full.names = T)) %>% 
  mutate(w = sum(spp_wts$w)/n())

provs_wts <- tibble(filepath = list.files(file.path(emLab_project_dir, "data", "02_processed", "biogeography"), full.names = T, pattern = "\\.tif")) %>% 
  mutate(w = sum(spp_wts$w)/n())

feature_wts <- c(spp_wts$w, smts_wts$w, provs_wts$w)
```

```{r}
global_bio_curve <- bio_benefit_curves %>% 
  select(-cell_id) %>% 
  as.matrix() %*% as.matrix(feature_wts) %>% 
  as_tibble() %>% 
  set_names("V") %>% 
  mutate(fraction_protected = 1/n(),
         cell_id = bio_benefit_curves$cell_id,
         fraction_protected = cumsum(fraction_protected)) %>% 
  filter(fraction_protected > fraction_in_MPA)
```

```{r}
national_benefit_curve <- read_csv(file.path(emLab_project_dir, "data", "03_output", "08_biodiversity_national", "benefit_curve.csv")) %>% 
  filter(fraction_protected > fraction_in_MPA)

random_benefit_curves <- list.files(file.path(emLab_project_dir, "data", "03_output", "09_biodiversity_random", "random_runs"),
                                    full.names = T) %>% 
  map(read_csv) %>% 
  reduce(bind_rows) %>% 
  filter(fraction_protected > fraction_in_MPA) %>% 
  mutate(V = scales::rescale(V))
```

```{r}
efficiency_plot <- ggplot()+
  geom_line(data = global_bio_curve %>% 
              mutate(V = scales::rescale(V)),
            aes(x = fraction_protected, y = V, col = "Global"))+
  geom_line(data = national_benefit_curve %>% 
              mutate(V = scales::rescale(V)),
            aes(x = fraction_protected, y = scales::rescale(V), col = "National"))+
  geom_rect(aes(xmin = 0, 
                xmax = fraction_in_MPA, 
                ymin = 0,
                ymax = 1),
            fill = "#5FAD41")+
  geom_line(data = random_benefit_curves ,
            aes(x = fraction_protected, y = V, col = "Random", group = run), alpha = 0.7)+
  labs(x = "Fraction Ocean Protected",
       y = "Biodiversity benefit",
       col = "")+
  theme_classic()+
  scale_x_continuous(expand = c(0,0), labels = c(0,0.25,0.5,0.75,1), breaks = c(0,0.25,0.5,0.75,1), limits = c(0,1))+
  scale_y_continuous(expand = c(0,0), labels = c(0,0.25,0.5,0.75,1), breaks = c(0,0.25,0.5,0.75,1))+
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        plot.margin = margin(0, 5, 0, 5, "cm"))+
  expand_limits(y = c(0, 1.01),
                x = c(0, 1.05))+
  scale_color_manual(values = c("#2D728F", "#D62839", "grey"),
                     labels = c("Global", "National", "Random"))
```

```{r}
fig_4 <- propeller_bio_plot + efficiency_plot + 
         plot_annotation(tag_levels = "a")+
         plot_layout(ncol = 1, heights = c(2.6, 1)) 

ggsave(fig_4, filename = file.path(emLab_project_dir, "figures", "main", "figure_4.pdf"), dpi = 300,  height = 15, width = 12)
ggsave(fig_4, filename = file.path(emLab_project_dir, "figures", "main", "figure_4.png"), dpi = 300,  height = 11, width = 14)
```

