---
title: "Figure 4: Multi-objective optimization"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
library(raster)
library(sf)
library(tidyverse)
library(patchwork)
library(cowplot)

source(here::here("common.R"))
```

# Effort Assumption 2

## Efficiency curve

```{r}
efficiency_curve_data <- read_rds(file.path(emLab_project_dir, "data","03_output", "13_efficiency_curve", "efficiency_curves.rds")) %>% 
  filter(effort_assumption == 2)

pts_of_interest <- bind_rows(efficiency_curve_data %>% 
                               slice(which.min(abs(bio_x_factor - 0))),
                             efficiency_curve_data %>% 
                               slice(which.min(abs(bio_x_factor - 1))),
                             efficiency_curve_data %>% 
                               slice(which.min(abs(delta_catch - 0)))) %>% 
  mutate(label = c("b", "c", "d"))

efficiency_curve <- ggplot()+
  geom_point(data = efficiency_curve_data, 
             aes(x = 100*bio_benefit, y = delta_catch/10^6, size = 100*fraction_protected, fill = 100*carbon_benefit), alpha = 0.9, shape = 21, col = "black")+
  scale_x_continuous(limits = c(0,100))+
  labs(x = "Total biodiversity benefit (%)", 
       y = "Change in catch (MMT)",
       fill = "% total carbon \nbenefits",
       size = "% ocean \nprotected")+
  scale_radius( breaks = rev(c(10, 30, 50, 70, 90)))+
  geom_hline(yintercept = 0, linetype = 2)+
  geom_segment(data = pts_of_interest %>% filter(bio_x_factor == 0),
               aes(x = 100*bio_benefit,
                   xend = 100*bio_benefit,
                   y = 0, 
                   yend = max(efficiency_curve_data$delta_catch)/10^6 + 1.8),
               linetype = 2)+
  geom_point(data = pts_of_interest, 
             aes(x = 100*bio_benefit, y = delta_catch/10^6), shape = 17)+
  ggrepel::geom_text_repel(data = pts_of_interest, 
                           aes(x = 100*bio_benefit, y = delta_catch/10^6, label = label))+
  annotate("text", label = "Biodiversity weight", x = 50, y = max(efficiency_curve_data$delta_catch)/10^6 + 5, size = 4, colour = "Black")+
  annotate("text", label = "0", 
           x = 100*pts_of_interest$bio_benefit[pts_of_interest$bio_x_factor == 0], 
           y = max(efficiency_curve_data$delta_catch)/10^6 + 3, size = 4, colour = "Black")+
  annotate("text", label = "lower", x = 0.5, y = max(efficiency_curve_data$delta_catch)/10^6 + 3, size = 4, colour = "Black")+
  annotate("text", label = "higher", x = 99, y = max(efficiency_curve_data$delta_catch)/10^6 + 3, size = 4, colour = "Black")+
  theme_classic()+
  scale_y_continuous(breaks = c(-40, -20, 0, 10))+
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 10))+
  geom_segment(aes(y = max(efficiency_curve_data$delta_catch)/10^6 + 1.5, 
                   yend = max(efficiency_curve_data$delta_catch)/10^6 + 1.5, 
                   x = 0, xend = 100),
               linejoin = 'mitre',
               arrow = arrow(ends = "both",length = unit(0.2, "cm")))+
  paletteer::scale_fill_paletteer_c("scico::roma", direction = -1)+
  guides(fill = guide_colorbar(frame.colour = "black", ticks.colour = "black"))
```

## radar plots

```{r}
radar_plot_b <- pts_of_interest %>% 
  mutate(delta_catch = delta_catch/max(delta_catch)) %>% 
  select(label, bio_benefit, delta_catch, carbon_benefit) %>% 
  set_names(c("label", "biodiversity", "food", "carbon")) %>% 
  filter(label == "b") %>% 
  ggradar::ggradar(group.point.size = 2, 
                   gridline.mid.colour	= "grey",
                   grid.label.size	= 3, 
                   group.line.width	= 1,
                   axis.label.size = 3,
                   group.colours = "#046C99") +
  theme_minimal()

radar_plot_c <- pts_of_interest %>% 
  mutate(delta_catch = delta_catch/max(delta_catch)) %>% 
  select(label, bio_benefit, delta_catch, carbon_benefit) %>% 
  set_names(c("label", "biodiversity", "food", "carbon")) %>% 
  filter(label == "c") %>% 
  ggradar::ggradar(group.point.size = 2, 
                   gridline.mid.colour	= "grey",
                   grid.label.size	= 3,
                   group.line.width	= 1,
                   axis.label.size = 3,
                   group.colours = "#046C99") +
  theme_minimal()

radar_plot_d <- pts_of_interest %>% 
  mutate(delta_catch = delta_catch/max(delta_catch)) %>% 
  select(label, bio_benefit, delta_catch, carbon_benefit) %>% 
  set_names(c("label", "biodiversity", "food", "carbon")) %>% 
  filter(label == "d") %>% 
  ggradar::ggradar(group.point.size = 2, 
                   gridline.mid.colour	= "grey",
                   grid.label.size	= 3,
                   group.line.width	= 1,
                   axis.label.size = 3,
                   group.colours = "#046C99") +
  theme_minimal()

theme_radar <- theme(legend.position = 'none',
                     legend.margin = margin(0,0,0,0),
                     text = element_text(family = "Ubuntu Regular", color = "#22211d"),
                     axis.line = element_blank(),
                     axis.text.x = element_blank(),
                     axis.text.y = element_blank(),
                     axis.ticks = element_blank(),
                     axis.title.x = element_blank(),
                     axis.title.y = element_blank(),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     plot.background = element_rect(fill = NA, color = NA), 
                     panel.background = element_rect(fill = NA, color = NA), 
                     panel.border = element_blank(),
                     plot.margin = margin(0, 0, 0, 0, "cm"))
```

```{r}
bottom_row <- plot_grid(radar_plot_b + theme_radar,
                        radar_plot_c + theme_radar,
                        radar_plot_d + theme_radar, 
                        labels = c('b','c', 'd'), 
                        label_size = 12,
                        label_fontface = "plain",
                        ncol = 3)

plot_grid(efficiency_curve, bottom_row, labels = c('a', ''), label_size = 12, ncol = 1, rel_heights = c(2.4,1),label_fontface = "plain" )+
  ggsave(file.path(emLab_project_dir, "figures", "main", "figure_3.pdf"),  dpi = 300,  height = 6, width = 8)

plot_grid(efficiency_curve, bottom_row, labels = c('a', ''), label_size = 12, ncol = 1, rel_heights = c(2.4,1),label_fontface = "plain" )+
  ggsave(file.path(emLab_project_dir, "figures", "main", "figure_3.png"),  dpi = 300,  height = 6, width = 8)
```


# Effort Assumption 1

## Efficiency curve

```{r}
efficiency_curve_data <- read_rds(file.path(emLab_project_dir, "data","03_output", "13_efficiency_curve", "efficiency_curves.rds")) %>% 
  filter(effort_assumption == 1)

pts_of_interest <- bind_rows(efficiency_curve_data %>% 
                               slice(which.min(abs(bio_x_factor - 0))),
                             efficiency_curve_data %>% 
                               slice(which.min(abs(bio_x_factor - 1))),
                             efficiency_curve_data %>% 
                               slice(which.min(abs(delta_catch - 0)))) %>% 
  mutate(label = c("b", "c", "d"))

efficiency_curve <- ggplot()+
  geom_point(data = efficiency_curve_data, 
             aes(x = 100*bio_benefit, y = delta_catch/10^6, size = 100*fraction_protected, fill = 100*carbon_benefit), alpha = 0.9, shape = 21, col = "black")+
  scale_x_continuous(limits = c(0,100))+
  labs(x = "Total biodiversity benefit (%)", 
       y = "Change in catch (MMT)",
       fill = "% total carbon \nbenefits",
       size = "% ocean \nprotected")+
  scale_radius( breaks = rev(c(10, 30, 50, 70, 90)))+
  geom_hline(yintercept = 0, linetype = 2)+
  geom_segment(data = pts_of_interest %>% filter(bio_x_factor == 0),
               aes(x = 100*bio_benefit,
                   xend = 100*bio_benefit,
                   y = 0, 
                   yend = max(efficiency_curve_data$delta_catch)/10^6 + 1.8),
               linetype = 2)+
  geom_point(data = pts_of_interest, 
             aes(x = 100*bio_benefit, y = delta_catch/10^6), shape = 2)+
  ggrepel::geom_text_repel(data = pts_of_interest, 
                           aes(x = 100*bio_benefit, y = delta_catch/10^6, label = label))+
  annotate("text", label = "Biodiversity weight", x = 50, y = max(efficiency_curve_data$delta_catch)/10^6 + 5, size = 4, colour = "Black")+
  annotate("text", label = "0", 
           x = 100*pts_of_interest$bio_benefit[pts_of_interest$bio_x_factor == 0], 
           y = max(efficiency_curve_data$delta_catch)/10^6 + 3, size = 4, colour = "Black")+
  annotate("text", label = "lower", x = 0.5, y = max(efficiency_curve_data$delta_catch)/10^6 + 3, size = 4, colour = "Black")+
  annotate("text", label = "higher", x = 99, y = max(efficiency_curve_data$delta_catch)/10^6 + 3, size = 4, colour = "Black")+
  theme_classic()+
  scale_y_continuous(breaks = c(-40, -20, 0, 10))+
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 10))+
  geom_segment(aes(y = max(efficiency_curve_data$delta_catch)/10^6 + 1.5, 
                   yend = max(efficiency_curve_data$delta_catch)/10^6 + 1.5, 
                   x = 0, xend = 100),
               linejoin = 'mitre',
               arrow = arrow(ends = "both",length = unit(0.2, "cm")))+
    paletteer::scale_fill_paletteer_c("scico::roma", direction = -1)+
  guides(fill = guide_colorbar(frame.colour = "black", ticks.colour = "black"))
```

## radar plots

```{r}
radar_plot_b <- pts_of_interest %>% 
  mutate(delta_catch = delta_catch/max(delta_catch)) %>% 
  select(label, bio_benefit, delta_catch, carbon_benefit) %>% 
  set_names(c("label", "biodiversity", "food", "carbon")) %>% 
  filter(label == "b") %>% 
  ggradar::ggradar(group.point.size = 2, 
                   gridline.mid.colour	= "grey",
                   grid.label.size	= 3, 
                   group.line.width	= 1,
                   axis.label.size = 3,
                   group.colours = "#046C99") +
  theme_minimal()

radar_plot_c <- pts_of_interest %>% 
  mutate(delta_catch = delta_catch/max(delta_catch)) %>% 
  select(label, bio_benefit, delta_catch, carbon_benefit) %>% 
  set_names(c("label", "biodiversity", "food", "carbon")) %>% 
  filter(label == "c") %>% 
  ggradar::ggradar(group.point.size = 2, 
                   gridline.mid.colour	= "grey",
                   grid.label.size	= 3,
                   group.line.width	= 1,
                   axis.label.size = 3,
                   group.colours = "#046C99") +
  theme_minimal()

radar_plot_d <- pts_of_interest %>% 
  mutate(delta_catch = delta_catch/max(delta_catch)) %>% 
  select(label, bio_benefit, delta_catch, carbon_benefit) %>% 
  set_names(c("label", "biodiversity", "food", "carbon")) %>% 
  filter(label == "d") %>% 
  ggradar::ggradar(group.point.size = 2, 
                   gridline.mid.colour	= "grey",
                   grid.label.size	= 3,
                   group.line.width	= 1,
                   axis.label.size = 3,
                   group.colours = "#046C99") +
  theme_minimal()

theme_radar <- theme(legend.position = 'none',
                     legend.margin = margin(0,0,0,0),
                     text = element_text(family = "Ubuntu Regular", color = "#22211d"),
                     axis.line = element_blank(),
                     axis.text.x = element_blank(),
                     axis.text.y = element_blank(),
                     axis.ticks = element_blank(),
                     axis.title.x = element_blank(),
                     axis.title.y = element_blank(),
                     panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     plot.background = element_rect(fill = NA, color = NA), 
                     panel.background = element_rect(fill = NA, color = NA), 
                     panel.border = element_blank(),
                     plot.margin = margin(0, 0, 0, 0, "cm"))
```

```{r}
bottom_row <- plot_grid(radar_plot_b + theme_radar,
                        radar_plot_c + theme_radar,
                        radar_plot_d + theme_radar, 
                        labels = c('b','c', 'd'), 
                        label_size = 12,
                        label_fontface = "plain",
                        ncol = 3)

plot_grid(efficiency_curve, bottom_row, labels = c('a', ''), label_size = 12, ncol = 1, rel_heights = c(2.4,1),label_fontface = "plain" )+
  ggsave(file.path(emLab_project_dir, "figures", "supplement", "efficiency_curve_a1.png"),  dpi = 300,  height = 6, width = 8)

plot_grid(efficiency_curve, bottom_row, labels = c('a', ''), label_size = 12, ncol = 1, rel_heights = c(2.4,1),label_fontface = "plain" )+
  ggsave(file.path(emLab_project_dir, "figures", "supplement", "efficiency_curve_a1.pdf"),  dpi = 300,  height = 6, width = 8)
```




