---
title: "Figure 2: Biodiversity in EEZ vs HS"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
library(raster)
library(sf)
library(tidyverse)
library(ggplot2)

DIR_GCS <- "~/gcs/git-annex/Carta-Marina"

DIR_GCS_data <- "~/gcs/spatial-datasets"

ocean_low_res_moll <- raster("~/gcs/spatial-datasets/ocean/ocean-low-res-moll.tif")

ocean_matrix <- ocean_low_res_moll %>% 
  raster::as.data.frame(xy = T) %>% 
  filter(ocean.low.res.moll == 1) %>% 
  mutate(cell_id = as.character(group_indices(., x, y))) %>% 
  select(-ocean.low.res.moll) %>% 
  as_tibble()

land_shp <- sf::read_sf("~/gcs/spatial-datasets/land/land_50.shp")

land_shp_moll <- land_shp %>% 
  st_transform(crs = projection(ocean_low_res_moll))

z_pal <- list(breaks = c(0, 0.2, 0.5, 0.7, 0.8, 0.85, 0.9, 0.95, 1),
              labels = c("0-20", "20-50", "50-70", "70-80", "80-85", "85-90", "90-95", "95-100"),
              colors = c("#4575b4", "#74add1", "#abd9e9", "#e0f3f8" ,"#fee090" ,"#fdae61" ,"#f46d43", "#d73027"))

```

# Read MPAS

```{r}
MPAs <- raster("../Zonation/data/masks/fully_highly_protected_reviewed_MPAs.tif")

MPAs_df <- MPAs %>% 
  raster::as.data.frame(xy = T) %>%
  inner_join(ocean_matrix) %>% 
  select(lon = x, lat = y, cell_id, mpa = fully_highly_protected_reviewed_MPAs) %>%
  as_tibble() 

fraction_in_MPA <- sum(!is.na(MPAs_df$mpa))/nrow(MPAs_df)
```

# Read EEZ vs High Seas mask

```{r}
eez_mask <- raster("../../../gcs/git-annex/Carta-Marina/masks/data/processed/EEZ_mask.tif") # 1 equals high seas

eez_mask_df_moll <- eez_mask %>% 
  as.data.frame(xy = TRUE) %>% 
  set_names(c("x", "y", "eez_mask")) %>% 
  mutate(eez_mask = ifelse(eez_mask == 1, 1, NA)) %>% 
  filter(!is.na(eez_mask)) %>% 
  inner_join(ocean_matrix)
```

# Mask and rescale

## High Seas 

```{r}
bio_ranking <- raster("../Juanation/05_spp_wts_smts_provs_MPAs/results/ranking_raster_with_impacts.tif")

HS_mask <- eez_mask %>% 
  mask(eez_mask, maskvalue = 0, updatevalue = NA, inverse = T) %>% 
  mask(ocean_low_res_moll)

HS_MPAs_df <- MPAs %>% 
  mask(HS_mask, mask_value = 0, updatevalue = NA) %>% 
  raster::as.data.frame(xy = T) %>%
  inner_join(ocean_matrix) %>% 
  select(lon = x, lat = y, cell_id, mpa = fully_highly_protected_reviewed_MPAs) %>%
  as_tibble() 

HS_bio_ranks <- bio_ranking %>% 
  mask(HS_mask, mask_value = 0, updatevalue = NA)
```

```{r}
HS_bio_ranking_df <- HS_bio_ranks %>% 
  as.data.frame(xy = TRUE) %>% 
  set_names(c("lon", "lat", "rank")) %>% 
  filter(!is.na(rank)) %>% 
  left_join(MPAs_df) %>% 
  mutate(rank = 100*rank)

fraction_HS_protected <- length(HS_bio_ranking_df$rank[!is.na(HS_bio_ranking_df$mpa)])/length(HS_bio_ranking_df$rank)

min_HS_MPA_rank <- min(HS_bio_ranking_df$rank[!is.na(HS_bio_ranking_df$mpa)])
```

```{r}
HS_breaks <- sort(unique(c(0, 50, 60, 70, 80, 85, 90, 95, min_HS_MPA_rank, 100)))

HS_labels <- HS_breaks[-1]

HS_colors <- z_pal$colors

HS_colors[HS_labels > min_HS_MPA_rank] <- "#47A025"

HS_labels <- 100 - HS_labels

HS_labels[HS_labels ==  (100-min_HS_MPA_rank)] <- " "

HS_legend_key_widths <- tibble(r = as.numeric(as.character(HS_breaks[-1]/100)),
                                  r_lag = lag(r)) %>% 
  replace_na(list(r_lag = 0)) %>%
  mutate(l = r - r_lag) %>% 
  mutate(w = ifelse(r <= 0.7, l/0.7*0.2, l/0.3*0.4),
         w1 = l*0.6) %>% pull(w1)

HS_legend_key_widths[length(HS_legend_key_widths)] <- HS_legend_key_widths[length(HS_legend_key_widths)]/4

HS_bio_map <- HS_bio_ranking_df %>% 
  mutate(rank_cut = cut(rank,
                        breaks = raster::quantile(HS_bio_ranking_df$rank,
                                                  probs = c(0.00, 0.20, 0.50 ,0.70, 0.80,0.85, 0.90, 0.95, 1 - fraction_HS_protected, 1.00)),
                        labels = HS_labels,
                        include.lowest = T)) %>% 
  ggplot()+
  geom_raster(aes(x = lon, y = lat, fill = rank_cut))+
  geom_raster(data = HS_MPAs_df %>% 
                filter(!is.na(mpa)), aes(x = lon, y = lat), fill = "#47A025")+
  geom_sf(data = land_shp_moll, col = "transparent", fill = "grey", inherit.aes = FALSE)+
  scale_fill_manual(values  = HS_colors,
                    guide = guide_legend(
                      title = "Top % of the High Seas",
                      direction = "horizontal",
                      keyheight = unit(0.01, "npc"),
                      keywidth = unit(rev(HS_legend_key_widths)/1.5, "npc"),
                      title.position = 'top',
                      title.hjust = 0.5,
                      label.hjust = -.02,
                      nrow = 1,
                      byrow = T,
                      reverse = T,
                      label.position = "bottom"))+
  theme(legend.text = element_text(size = 6),
        legend.text.align = 0,
        legend.position = "bottom",
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = NA, color = NA), 
        panel.background = element_rect(fill = NA, color = NA), 
        legend.background = element_rect(fill = NA, color = NA),
        panel.border = element_blank())
```

## EEZ 

```{r}
EEZ_MPAs_df <- MPAs %>% 
  mask(HS_mask, mask_value = 0, updatevalue = NA, inverse = T) %>% 
  raster::as.data.frame(xy = T) %>%
  inner_join(ocean_matrix) %>% 
  select(lon = x, lat = y, cell_id, mpa = fully_highly_protected_reviewed_MPAs) %>%
  as_tibble() 

EEZ_bio_ranks <- bio_ranking %>% 
  mask(HS_mask, mask_value = 0, updatevalue = NA, inverse = T)
```

```{r}
EEZ_bio_ranking_df <- EEZ_bio_ranks %>% 
  as.data.frame(xy = TRUE) %>% 
  set_names(c("lon", "lat", "rank")) %>% 
  filter(!is.na(rank)) %>% 
  left_join(MPAs_df) %>% 
  mutate(rank = 100*rank)

fraction_EEZ_protected <- length(EEZ_bio_ranking_df$rank[!is.na(EEZ_bio_ranking_df$mpa)])/length(EEZ_bio_ranking_df$rank)

min_EEZ_MPA_rank <- min(EEZ_bio_ranking_df$rank[!is.na(EEZ_bio_ranking_df$mpa)])
```

```{r}
EEZ_breaks <- sort(unique(c(0, 50, 60, 70, 80, 85, 90, 95, min_EEZ_MPA_rank, 100)))

EEZ_labels <- EEZ_breaks[-1]

EEZ_colors <- z_pal$colors

EEZ_colors[EEZ_labels > min_EEZ_MPA_rank] <- "#47A025"

EEZ_labels <- 100 - EEZ_labels

EEZ_labels[EEZ_labels ==  (100-min_EEZ_MPA_rank)] <- " "

EEZ_legend_key_widths <- tibble(r = as.numeric(as.character(EEZ_breaks[-1]/100)),
                                  r_lag = lag(r)) %>% 
  replace_na(list(r_lag = 0)) %>%
  mutate(l = r - r_lag) %>% 
  mutate(w = ifelse(r <= 0.7, l/0.7*0.2, l/0.3*0.4),
         w1 = l*0.6) %>% pull(w1)

EEZ_legend_key_widths[length(EEZ_legend_key_widths)] <- 0.03*0.9
EEZ_legend_key_widths[length(EEZ_legend_key_widths) -1] <- 0.03 - 0.03*0.9

EEZ_bio_map <- EEZ_bio_ranking_df %>% 
  mutate(rank_cut = cut(rank,
                        breaks = raster::quantile(EEZ_bio_ranking_df$rank,
                                                  probs = c(0.00, 0.20, 0.50 ,0.70, 0.80,0.85, 0.90, 0.95, 1 - fraction_EEZ_protected, 1.00)),
                        labels = EEZ_labels,
                        include.lowest = T)) %>% 
  ggplot()+
  geom_raster(aes(x = lon, y = lat, fill = rank_cut))+
  geom_raster(data = EEZ_MPAs_df %>% 
                filter(!is.na(mpa)), aes(x = lon, y = lat), fill = "#47A025")+
  geom_sf(data = land_shp_moll, col = "transparent", fill = "grey", inherit.aes = FALSE)+
  scale_fill_manual(values  = EEZ_colors,
                    guide = guide_legend(
                      title = "Top % of the Exclusive Economic Zones",
                      direction = "horizontal",
                      keyheight = unit(0.01, "npc"),
                      keywidth = unit(rev(EEZ_legend_key_widths)/1.5, "npc"),
                      title.position = 'top',
                      title.hjust = 0.5,
                      label.hjust = -.02,
                      nrow = 1,
                      byrow = T,
                      reverse = T,
                      label.position = "bottom"))+
  theme(legend.text = element_text(size = 6),
        legend.text.align = 0,
        legend.position = "bottom",
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = NA, color = NA), 
        panel.background = element_rect(fill = NA, color = NA), 
        legend.background = element_rect(fill = NA, color = NA),
        panel.border = element_blank())
```

# Make Figure 2

```{r}
library(patchwork)

ext_figure_1 <- EEZ_bio_map + 
  HS_bio_map + 
  plot_annotation(tag_levels = "a")+
  plot_layout(ncol = 1) +
  theme(plot.margin = grid::unit(c(0,0,0,0), "mm")) 

ggsave(ext_figure_1, filename = "ext_figure_1.pdf", dpi = 300,  height = 9, width = 8)
ggsave(ext_figure_1, filename = "ext_figure_1.png", dpi = 300,  height = 9, width = 8)
```

