---
title: "13_efficiency_curve"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
library(raster)
library(sf)
library(tidyverse)
library(patchwork)
library(parallel)
library(foreach)
library(doParallel)

source(here::here("common.R"))

variant_name <- "13_efficiency_curve"

variant_dir <- file.path(emLab_project_dir,"data", "03_output", variant_name)

dir.create(variant_dir)
```

# Load features data 

## Biodiversity 

```{r}
bio_df <- data.table::fread(file.path(emLab_project_dir, "data", "02_processed", "features_df", "all_bio_features_df.csv"))

bio_feature_names <- colnames(bio_df)[c(-1,-2,-3)]

n_bio_features <- length(bio_feature_names)

spp_wts <- data.table::fread(file.path(emLab_project_dir, "data", "02_processed", "species_list", "spp_weights.csv")) %>% 
  as_tibble() %>% 
  rename(w = spp_weight)

smts_wts <- tibble(filepath = list.files(file.path(emLab_project_dir, "data", "02_processed","seamounts"), full.names = T)) %>% 
  mutate(w = sum(spp_wts$w)/n())

provs_wts <- tibble(filepath = list.files(file.path(emLab_project_dir, "data", "02_processed", "biogeography"), full.names = T, pattern = "\\.tif")) %>% 
  mutate(w = sum(spp_wts$w)/n())

bio_features_info <- bind_rows(spp_wts %>% 
                                 mutate(sub_goal = "species"), 
                               smts_wts %>% 
                                 mutate(sub_goal = "seamounts"), 
                               provs_wts %>% 
                                 mutate(sub_goal = "provinces"))

z_bio <- 0.25
```

## Food

```{r}
stocks_df <- data.table::fread(file.path(emLab_project_dir, "data", "02_processed", "features_df", "stocks_df.csv")) %>% 
  as_tibble()

stocks <- tibble(filename = list.files(file.path(emLab_project_dir, "data", "02_processed", "stock_distributions"),
                                       full.names = T),
                 stockid = str_remove(basename(filename), "\\.tif"))

stocks_info <- read_csv(file.path(emLab_project_dir,"data", "02_processed", "food_provision", "MegaData_UncertaintyAnalysis.csv")) %>%
  select(stockid, k = Kfin, ex_rate = ExploitationRate_BAU1, m = m_fin, r = r_fin)

stocks_info <- stocks %>%
  left_join(stocks_info)

stocks_info$ex_rate[stocks_info$ex_rate >= 1] <- 0.99999

n_stocks <- nrow(stocks_info)

stock_names <- colnames(stocks_df)[c(-1,-2,-3)]
```

## Carbon 

```{r}
carbon_df <- data.table::fread(file.path(emLab_project_dir, "data", "02_processed", "features_df", "carbon_df.csv")) %>% 
  as_tibble()

n_carbon <- 1

z_carbon <- 1
```

```{r}
features_df <- bio_df %>% 
  left_join(carbon_df) %>% 
  left_join(stocks_df)

n_features <- n_stocks + n_carbon + n_bio_features
```

# Within-goal weights

```{r}
bio_weights <- bio_features_info$w

names(bio_weights) <- bio_feature_names

carbon_weights <- c("carbon" = 1)

food_weights <- rep(1, n_stocks)

names(food_weights) <- stock_names
```

# Normalize and trim the data

```{r}
features_matrix <- features_df %>% 
  select(-x,-y,-cell_id) %>% 
  as.matrix()

stopifnot(
  sum(map_lgl(features_df %>%
                select(-x,-y,-cell_id), is.numeric)) == ncol(features_matrix)
  ) # ALL numeric?

Norm_features_matrix <- sweep(features_matrix, 2, colSums(features_matrix, na.rm = T), FUN = "/")

rownames(Norm_features_matrix) <- features_df$cell_id

stopifnot(
  sum(colSums(Norm_features_matrix, na.rm = T)) == ncol(features_matrix)
  )  # Normalized OK?

dim(Norm_features_matrix)

Norm_features_matrix <- Norm_features_matrix[rowSums(is.na(Norm_features_matrix)) != n_features, ]

stopifnot(
  identical(colnames(Norm_features_matrix),
          features_df %>%
            select(-x,-y,-cell_id) %>%
            colnames())
  )  # Is the order of the features mantained?
```

# Current MPAs

```{r}
MPAs <- raster(file.path(emLab_project_dir, "data", "02_processed", "masks", "fully_highly_protected_reviewed_MPAs.tif"))

MPAs_df <- MPAs %>% 
  raster::as.data.frame(xy = T) %>%
  inner_join(ocean_matrix) %>% 
  select(x, y, cell_id, mpa = fully_highly_protected_reviewed_MPAs) %>%
  as_tibble() 

fraction_in_MPA <- sum(!is.na(MPAs_df$mpa))/nrow(MPAs_df)
  
MPA_vect <- rownames(Norm_features_matrix) %>% 
  enframe() %>% 
  select(cell_id = value) %>% 
  left_join(MPAs_df) %>% 
  mutate(mpa =  !is.na(mpa)) %>% pull(mpa)
```

# Apply impacts

## Biodiversity

```{r}
bio_abatable_impacts_df <- raster(file.path(emLab_project_dir, 
                                            "data", "02_processed", "impacts", "chi", "abatable_impacts_5_yr_avg_log.tif")) %>% 
  raster::as.data.frame(xy = T) %>% 
  set_names(c("x", "y", "Ia")) %>% 
  inner_join(ocean_matrix) %>% 
  as_tibble() %>% 
  replace_na(list(Ia = 0))

bio_unabatable_impacts_df <- raster(file.path(emLab_project_dir, 
                                              "data", "02_processed", "impacts", "chi", "unabatable_impacts_5_yr_avg_log.tif")) %>% 
  raster::as.data.frame(xy = T) %>% 
  set_names(c("x", "y", "Iu")) %>% 
  inner_join(ocean_matrix) %>% 
  as_tibble()%>% 
  replace_na(list(Iu = 0))

bio_remains_BAU <- Norm_features_matrix[, bio_feature_names] %>% 
  sweep(1, (1 - bio_abatable_impacts_df$Ia), FUN = "*") %>% 
  sweep(1, (1 - bio_unabatable_impacts_df$Iu), FUN = "*") %>% 
  colSums(na.rm = T)

sum(bio_remains_BAU^z_bio*bio_weights)/sum(1^z_bio*bio_weights)

bio_remains_MPA <- Norm_features_matrix[, bio_feature_names] %>% 
  sweep(1, (1 - bio_unabatable_impacts_df$Iu), FUN = "*") %>% 
  colSums(na.rm = T)

#(sum(bio_remains_MPA^0.25*bio_weights) - sum(bio_remains_BAU^0.25*bio_weights))/ sum(bio_remains_BAU^0.25*bio_weights)

bio_diff_matrix <- Norm_features_matrix[, bio_feature_names] %>% 
  sweep(1, (bio_abatable_impacts_df$Ia - bio_abatable_impacts_df$Ia*bio_unabatable_impacts_df$Iu), FUN = "*")

bio_diff_made <- colSums(bio_diff_matrix, na.rm = T)

Norm_features_matrix[, bio_feature_names] <- bio_diff_matrix
```

## Carbon

```{r}
carbon_abatable_impacts_df <- raster(file.path(emLab_project_dir, 
                                            "data", "02_processed", "impacts", "bottom_trawling", "abatable_impact_carbon_svr.tif")) %>% 
  raster::as.data.frame(xy = T) %>% 
  set_names(c("x", "y", "Ia")) %>% 
  inner_join(ocean_matrix) %>% 
  as_tibble() %>% 
  replace_na(list(Ia = 0)) %>% 
  filter(cell_id %in% rownames(Norm_features_matrix))

carbon_abatable_impacts_df <- carbon_abatable_impacts_df %>% 
  mutate(Ia = if_else(Ia == 0, 10^-6, Ia))

carbon_remains_BAU <- Norm_features_matrix[, "carbon", drop = F] %>% 
  sweep(1, (1 - carbon_abatable_impacts_df$Ia), FUN = "*") %>% 
  colSums(na.rm = T)

carbon_remains_MPA <- Norm_features_matrix[, "carbon", drop = F] %>% 
  sweep(1, (1 - 0), FUN = "*") %>% 
  colSums(na.rm = T)

carbon_diff_matrix <- Norm_features_matrix[, "carbon", drop = F] %>% 
  sweep(1, (carbon_abatable_impacts_df$Ia), FUN = "*")

carbon_diff_made <- colSums(carbon_diff_matrix, na.rm = T)

Norm_features_matrix[, "carbon"] <- carbon_diff_matrix

Norm_features_matrix[is.na(Norm_features_matrix)] <- 0

write_rds(Norm_features_matrix, 
          file.path(variant_dir, "multi_objective_norm_features_diff_matrix.rds"))
```

# Initial conditions

```{r}
protected_cells <- matrix(MPA_vect, nrow = 1, ncol = nrow(Norm_features_matrix))

unprotected_matrix <- Norm_features_matrix[!protected_cells, ]

protected_matrix <- Norm_features_matrix[protected_cells, ]
```

```{r}
baseline_state <- protected_cells%*%Norm_features_matrix

baseline_state[,"carbon"] <- baseline_state[, "carbon"] + carbon_remains_BAU

baseline_state[, bio_feature_names] <- baseline_state[, bio_feature_names] + bio_remains_BAU
```

```{r}
max_slopes_bio <- z_bio*baseline_state[, bio_feature_names]^(z_bio - 1)

#max_slopes_bio[which(!is.finite(max_slopes_bio))] <- 0

max_slope_carbon <- 1

names(max_slope_carbon) <- "carbon"

estimate_food_slopes <- function(e = stocks_info$ex_rate, 
                                 m = stocks_info$m,
                                 r = stocks_info$r, 
                                 k = stocks_info$k,
                                 R){
  
  slope <- -e*k*m*(m + e)*((e*r + 2*e*m)*R + m*r - 2*e*m)/(r*(e*R + m)^3)
  
  return(slope)
  
}

max_slopes_food <- estimate_food_slopes(R = matrixStats::colMaxs(unprotected_matrix[, stock_names], na.rm = T))

names(max_slopes_food) <- stock_names

max_slopes <- c(max_slopes_bio, max_slope_carbon, max_slopes_food)
```

# Slopes function

```{r}
estimate_current_slopes <- function(x, g, wts){
  
  slopes <- vector(mode = "numeric", length = n_features)

  slopes[g == 1] <- pmin(max_slopes_bio, z_bio*x[g == 1]^(z_bio - 1))*wts[g == 1]
  
  slopes[g == 2] <- pmin(max_slope_carbon, z_carbon*x[g == 2]^(z_carbon - 1))*wts[g == 2]
    
  slopes[g == 3] <- estimate_food_slopes(R = x[g == 3])*wts[g == 3]
    
  return(slopes)
  
}

# where g is a vector that identifies each feature as part of each goal: bio (1), carbon (2), food (3)
group_ids <- c(rep(1, n_bio_features), rep(2, n_carbon), rep(3, n_stocks))
```

# Preferences

```{r}
max_food_delta <- read_csv(file.path(emLab_project_dir, "data", "03_output", "07_food", "results_per_pixel.csv")) %>% 
  summarize(max_deltaH = max(network_cummulative_delta_catch),
            max_deltaH_bau =  max(network_cummulative_delta_catch[is_mpa == 1])) %>% 
  transmute(max_deltaH - max_deltaH_bau) %>% 
  pull()

max_bio_delta <- sum(bio_remains_MPA^z_bio*bio_weights) - sum(bio_remains_BAU^z_bio*bio_weights)

max_carbon_delta <- sum(carbon_remains_MPA*carbon_weights) - sum(carbon_remains_BAU*carbon_weights)

alpha_C <- 0

alpha_F <- 1250

alpha_B <- round(unique(c(-seq(from = 0, by = max_food_delta*alpha_F/max_bio_delta, length.out = 25),
                          seq(from = 0, by = max_food_delta*alpha_F/max_bio_delta, length.out = 25))))

alpha_B <- c(alpha_B, round(seq(-max_food_delta*alpha_F/max_bio_delta, max_food_delta*alpha_F/max_bio_delta, length.out = 51)))

length(alpha_B)
```

```{r}
read_rds(file.path(emLab_project_dir, "data", "03_output", "05_spp_wts_smts_provs_MPAs","ranking_results.rds")) %>% 
  summarise(sum(delta)) %>% pull()

food_optim_rank <- read_rds("07_food/results/ranking_results_bau_1.rds")

max_food <- food_optim_rank %>% 
  filter(delta >= 0) %>% 
  summarise(sum(delta)) %>% pull()

alpha_C <- 0
alpha_F <- 1250

alpha_B <- round(unique(c(-seq(from = 0, by = max_food*alpha_F/max_bio, length.out = 25),
                          seq(from = 0, by = max_food*alpha_F/max_bio, length.out = 25))))

alpha_B <- c(alpha_B, round(seq(-max_food*alpha_F/max_bio, max_food*alpha_F/max_bio, length.out = 30)))

done_alphas <- as.numeric(str_remove(str_remove(list.files("13_efficiency_curve/results/", pattern = "ranking"), "ranking_"), ".rds"))

remaining_alphas <- alpha_B[!alpha_B %in% done_alphas]
```

# Ranking 

```{r}
rm(list = setdiff(ls(), c("bio_weights","carbon_weights","alpha_C","alpha_F","food_weights","alpha_B", "baseline_state", "OG_unprotected_matrix", "output_dir", "feature_wts", 
                          "param_e", "param_m", "param_r", "param_k", "z_vector", "p_vector", "ocean_matrix", "stock_names", "stocks_info", "bio_feature_names","bio_remains_BAU", "MPAs_df","estimate_current_slope", "food_foo", "max_slopes",  "carbon_weights", "carbon_remains_BAU", "remaining_alphas")))

gc()

registerDoParallel(cores = 15)

foreach (i = remaining_alphas) %dopar% {
  
  feature_weigths <- c(bio_weights*i, 
                       carbon_weights*alpha_C, 
                       food_weights*alpha_F)
  
  ranking <- list()
  
  current_pick <- 0
  
  current_state <- baseline_state 
  
  unprotected_matrix <- OG_unprotected_matrix
  
  while(nrow(unprotected_matrix) > 0){
    
    current_pick <- sum(current_pick, 1)
    
    slopes <- estimate_current_slope(param_e, param_m, param_r, param_k, current_state, p_vector, z_vector, wts = feature_weigths)
    
    delta <- unprotected_matrix%*%as.matrix(t(slopes))
    
    best_cell_indeces <- doBy::which.maxn(delta, n = 100)
    
    best_cells <- delta[best_cell_indeces,] %>% 
      enframe() %>% 
      set_names(c('cell_id', "delta")) %>% 
      mutate(pick_order = current_pick)
    
    ranking <- bind_rows(ranking, best_cells)
    
    current_state <- unprotected_matrix[best_cell_indeces, , drop = F] %>% 
      colSums() +
      current_state
    
    unprotected_matrix <- unprotected_matrix[-best_cell_indeces, , drop = F]
    
  }
  
  write_rds(ranking, paste0("13_efficiency_curve/results/ranking_",i,".rds"))
  
  optimal_fraction_protected <- MPAs_df %>% 
    filter(!is.na(mpa)) %>% 
    select(cell_id) %>% 
    bind_rows(ranking) %>% 
    mutate(is_mpa = is.na(delta)) %>% 
    full_join(ocean_matrix) %>% 
    mutate(fraction_protected = 1/n(),
           fraction_protected = cumsum(fraction_protected)) %>% 
    filter(delta == min(delta[delta >= 0], na.rm = T)) %>% 
    pull(fraction_protected) %>% 
    min()
 
  representation_curves <- MPAs_df %>% 
    filter(!is.na(mpa)) %>% 
    select(cell_id) %>% 
    bind_rows(ranking) %>% 
    mutate(is_mpa = is.na(delta)) %>% 
    full_join(ocean_matrix) %>% 
    left_join(OG_unprotected_matrix %>% 
                as_tibble(rownames = NA) %>% 
                rownames_to_column("cell_id")) %>% 
    replace(is.na(.), 0) %>% 
    mutate_all(.funs = cumsum)
  
  food_delta_V <- representation_curves[, stock_names] %>% 
    apply(MARGIN = 1, 
          function(x) stocks_info$ex_rate*(stocks_info$m*stocks_info$k*(1 - x)/(stocks_info$ex_rate*x+stocks_info$m))*(1 - (stocks_info$ex_rate*(1-x)*stocks_info$m)/((stocks_info$ex_rate*x + stocks_info$m)*stocks_info$r)) 
          - stocks_info$ex_rate*((stocks_info$r - stocks_info$ex_rate)/stocks_info$r)*stocks_info$k) %>% 
    t() %>% 
    rowSums() %>% 
    enframe() %>% 
    mutate(fraction_protected = 1/n(),
           fraction_protected =  cumsum(fraction_protected)) %>% 
    rename(delta_catch = value) %>% 
    select(-name)
  
  bio_benefit_curve <- representation_curves[, bio_feature_names] %>% 
    sweep(MARGIN = 2, bio_remains_BAU, `+`) %>%
    mutate_all(.funs = ~(.)^0.25) %>% 
    as.matrix() %*% as.matrix(bio_weights) %>% 
    as_tibble() %>% 
    set_names("V") %>% 
    mutate(fraction_protected = 1/n(),
           fraction_protected = cumsum(fraction_protected),
           V_rescaled = scales::rescale(V, c(0,1)))
  
  carbon_benefit_curve <- representation_curves[, "carbon"] %>% 
    sweep(MARGIN = 2, carbon_remains_BAU, `+`) %>%
    mutate_all(.funs = ~(.)^1) %>% 
    as.matrix() %*% as.matrix(carbon_weights) %>% 
    as_tibble() %>% 
    set_names("V") %>% 
    mutate(fraction_protected = 1/n(),
           fraction_protected = cumsum(fraction_protected),
           V_rescaled = scales::rescale(V, c(0,1)))
  
  result <- tibble(alpha_bio = i,
                   optim_protection = optimal_fraction_protected,
                   bio_benefit = bio_benefit_curve$V_rescaled[bio_benefit_curve$fraction_protected == optimal_fraction_protected],
                   carbon_benefit = carbon_benefit_curve$V_rescaled[carbon_benefit_curve$fraction_protected == optimal_fraction_protected],
                   delta_catch = food_delta_V$delta_catch[food_delta_V$fraction_protected == optimal_fraction_protected])
  
  
  write_rds(result, paste0("13_efficiency_curve/results/results_", i,".rds"))
  
}
```

# Results

```{r}
filenames <- list.files(output_dir, full.names = T, pattern = "result")

cost_curve_data <- filenames %>% 
  map(read_rds) %>% 
  bind_rows() %>% 
  arrange(desc(optim_protection))

write_csv(cost_curve_data, 
          file.path(output_dir, "summary.csv"))
```

```{r}
cost_curve_data <- read_csv(file.path(output_dir, "summary.csv"))

cost_curve_data %>% 
  slice(which.min(abs(bio_benefit - 0.66)))
```

```{r}
cost_curve_data %>% 
  ggplot()+
  geom_point(aes(x = 100*optim_protection, y = delta_catch/10^6, col = alpha_bio/10^6, size = 100*bio_benefit), alpha = 0.9)+
  scale_x_continuous(limits = c(0,100))+
  labs(x = "Ocean protected (%)", 
       y = "Change in catch (Million MT)",
       col = "Biodiveristy weight\n(million $ per unit)",
       size = "% Biodiveristy \nbenefits")+
  scale_radius( breaks = c(20, 40, 60, 80, 90))+
  geom_hline(yintercept = 0, linetype = 2)+
  theme_classic()+
  paletteer::scale_color_paletteer_c(package = "ggthemes", palette = "Classic Red-Blue")+
    ggsave(file.path(figs_output_dir, "protection_vs_delta_catch.png"),
          width = 8, height = 4)
```


```{r}
cost_curve_data %>% 
  ggplot()+
  geom_point(aes(x = 100*bio_benefit, y = -delta_catch/10^6, col = alpha_bio/10^6, size = 100*optim_protection))+
  labs(x = "% Biodiversity benefits", 
       y = "Costs (Forgone Catch MMT)",
       col = "Biodiveristy weight \n(million $ per unit)",
       size = "Optimal % Ocean")+
  geom_linerange(ymin = -max(cost_curve_data$delta_catch)/10^6, 
                 ymax = -cost_curve_data$delta_catch[which.min(abs(cost_curve_data$bio_benefit - 0.9))]/10^6,
                 x = 90,
                 linetype = 3)+
  geom_segment(y = -cost_curve_data$delta_catch[which.min(abs(cost_curve_data$bio_benefit - 0.9))]/10^6,
               yend = -cost_curve_data$delta_catch[which.min(abs(cost_curve_data$bio_benefit - 0.9))]/10^6,
                 x = 0,
                 xend = 90,
                 linetype = 3)+
  theme_dark()+
  scale_radius( breaks = c(20, 40, 60, 80, 90))+
  scale_color_gradient2(low = "#b2182b", mid = "#f7f7f7",high = "#2166ac")+
  ggsave(file.path(figs_output_dir, "bio_benefits_vs_costs.png"),
          width = 8, height = 4)
```


```{r}
cost_curve_data %>% 
  ggplot()+
  geom_point(aes(x = alpha_bio, y = bio_benefit))+
  ggsave(file.path(figs_output_dir, "alpha_bio_vs_bio_benefit.png"),
          width = 8, height = 4)
```

# Map of the cheapest X% biodiversity

```{r}
percent_bio <- 0.9

optim_alpha_bio <- cost_curve_data %>% 
  slice(which.min(abs(bio_benefit - percent_bio))) %>% 
  pull(alpha_bio)

optim_percent_protected <- cost_curve_data %>% 
  slice(which.min(abs(bio_benefit - percent_bio))) %>% 
  pull(optim_protection)

ranking_percent_bio <- str_subset(list.files(output_dir, full.names = T, pattern = "ranking"), as.character(optim_alpha_bio))[2] %>% 
  read_rds()

ranking_raster_percent_bio <- MPAs_df %>% 
  filter(!is.na(mpa)) %>% 
  select(cell_id) %>% 
  bind_rows(ranking_percent_bio) %>% 
  mutate(is_mpa = is.na(delta)) %>% 
  left_join(ocean_matrix) %>% 
  tibble::rowid_to_column("ID") %>% 
  mutate(rank = 1- scales::rescale(ID)) %>% 
  select(x, y, rank) %>% 
  rasterFromXYZ(crs = crs(ocean_low_res_moll)) %>% 
  projectRaster(ocean_low_res_moll) %>% 
  mask(ocean_low_res_moll)
  
ranking_raster_percent_bio <-   ranking_raster_percent_bio %>% 
  mask(ranking_raster_percent_bio >= (1 - optim_percent_protected), maskvalue = 0) 

ranking_df <- ranking_raster_percent_bio %>% 
  as.data.frame(xy = TRUE, centroids = T) %>% 
  set_names(c("lon", "lat", "rank")) %>% 
  mutate(rank = rank) %>% 
  filter(!is.na(rank))

min_rank <- min(ranking_df$rank)

min_MPA_global_rank <- ranking_raster_percent_bio %>% 
  mask(MPAs) %>% 
  cellStats(function(x, ...) min(x, na.rm = T)) %>% 
  as.numeric()

global_breaks <- c(0, 0.3, 0.5, 0.7, 0.8, 0.85, 0.9, 0.95, 1)

out_of_bounds <- length(global_breaks[global_breaks <= min_rank]) - 1

global_breaks <- tail(global_breaks, -out_of_bounds)

global_colors <- c("#4575b4", "#74add1", "#abd9e9", "#e0f3f8", "#fee090", "#fdae61", "#f46d43", "#d73027", "#4575b4")

global_colors <- tail(global_colors, -out_of_bounds)

local_breaks <- sort(unique(c(global_breaks, min_MPA_global_rank)))

local_labels <- local_breaks[-1]

local_colors <- global_colors

local_colors[local_labels > min_MPA_global_rank] <- "#47A025"

local_labels <- 100 - 100*local_labels

local_labels[local_labels ==  (100-100*min_MPA_global_rank)] <- " "

global_legend_key_widths <- tibble(to = as.numeric(as.character(local_breaks[-1])),
                                   from = lag(to)) %>% 
  replace_na(list(from = 0)) %>%
  mutate(range = to - from) %>% 
  mutate(w = range*0.6) %>% 
  mutate(w2 = if_else(to <= 0.8, w/1.5, w))

ranking_df %>% 
  mutate(rank_cut = cut(rank, 
                        breaks = local_breaks,
                        labels = local_breaks[-1],
                        include.lowest = T)) %>% 
  ggplot(aes(x = lon, y = lat))+
  geom_raster(aes(fill = rank_cut))+
  geom_raster(data = MPAs_df %>% 
                filter(!is.na(mpa)), aes(x = x, y = y), fill = "#47A025")+
  geom_sf(data = land_shp_moll, col = "transparent", fill = "grey", inherit.aes = FALSE)+
  scale_fill_manual(values  = local_colors,
                    labels = local_labels,
                    guide = guide_legend(title = "Top priority (%) ",
                                         direction = "horizontal",
                                         keyheight = unit(0.01, "npc"),
                                         #keywidth = unit(rev(global_legend_key_widths$w2), "npc"),
                                         title.position = 'top',
                                         title.hjust = 0.5,
                                         label.hjust = -.02,
                                         nrow = 1,
                                         byrow = T,
                                         reverse = T,
                                         label.position = "bottom"))+
  theme(legend.text = element_text(size = 6),
                    legend.text.align = 0,
                    legend.position = "bottom",
                    legend.background = element_rect(fill = NA, color = NA),
                    axis.text.x = element_text(size = 6),
                    axis.text.y = element_text(size = 6),
                    axis.ticks = element_blank(),
                    axis.line = element_blank(),
                    axis.title.x = element_blank(),
                    axis.title.y = element_blank(),
                    plot.background = element_rect(fill = NA, color = NA), 
                    panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
                    panel.grid.minor = element_blank(),
                    panel.background = element_rect(fill = NA, color = NA), 
                    panel.border = element_blank())+
  ggsave(filename = file.path(DIR_GCS, "Supplement", paste0("fig_cheapest_", round(100*percent_bio),"_percent_bio.png")),
         dpi = 300)
```

# Cheapest 30% of the ocean

```{r}
alpha_bio_30p <- cost_curve_data %>% 
  slice(which.min(abs(optim_protection - 0.3))) %>% 
  pull(alpha_bio)

ranking_cheapest_30p <- str_subset(list.files(output_dir, full.names = T, pattern = "ranking"), as.character(alpha_bio_30p))[2] %>% 
  read_rds()

ranking_raster_cheapest_30p <- MPAs_df %>% 
  filter(!is.na(mpa)) %>% 
  select(cell_id) %>% 
  bind_rows(ranking_cheapest_30p) %>% 
  mutate(is_mpa = is.na(delta)) %>% 
  left_join(ocean_matrix) %>% 
  tibble::rowid_to_column("ID") %>% 
  mutate(rank = 1- scales::rescale(ID)) %>% 
  select(x, y, rank) %>% 
  rasterFromXYZ(crs = crs(ocean_low_res_moll)) %>% 
  projectRaster(ocean_low_res_moll) %>% 
  mask(ocean_low_res_moll)
  
plot(ranking_raster_cheapest_30p)

ranking_raster_cheapest_30p <-   ranking_raster_cheapest_30p %>% 
  mask(ranking_raster_cheapest_30p >= (1 - 0.3), maskvalue = 0)

writeRaster(ranking_raster_cheapest_30p, filename = "13_efficiency_curve/results/cheapest_30p_raster.tif")
```

