---
title: "Upgrading weak MPAs"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
library(raster)
library(sf)
library(tidyverse)
library(scales)

DIR_GCS <- "~/gcs/git-annex/Carta-Marina"

DIR_GCS_data <- "~/gcs/spatial-datasets"

ocean_low_res_moll <- raster("~/gcs/spatial-datasets/ocean/ocean-low-res-moll.tif")

ocean_matrix <- ocean_low_res_moll %>% 
  raster::as.data.frame(xy = T) %>% 
  filter(ocean.low.res.moll == 1) %>% 
  mutate(cell_id = as.character(group_indices(., x, y))) %>% 
  select(-ocean.low.res.moll) %>% 
  as_tibble()

land_shp <- sf::read_sf("~/gcs/spatial-datasets/land/land_50.shp")

land_shp_moll <- land_shp %>% 
  st_transform(crs = projection(ocean_low_res_moll))

z_pal <- list(breaks = c(0, 0.2, 0.5, 0.7, 0.8, 0.85, 0.9, 0.95, 1),
              labels = c("0-20", "20-50", "50-70", "70-80", "80-85", "85-90", "90-95", "95-100"),
              colors = c("#4575b4", "#74add1", "#abd9e9", "#e0f3f8" ,"#fee090" ,"#fdae61" ,"#f46d43", "#d73027"))

variant_name <- "14_upgrade_weak_MPAs"

output_dir <- file.path(variant_name, "results")

figs_output_dir <- file.path(variant_name, "figures")

dir.create(variant_name)

dir.create(figs_output_dir)

dir.create(output_dir)
```

# Load data 

```{r}
spp_df <- data.table::fread("data/spp_df.csv") %>% 
  as_tibble()

spp_info <- data.table::fread("data/spp_weights.csv") %>% 
  as_tibble() %>% 
  rename(w = spp_weight)

smts_df <- data.table::fread("data/smts_df.csv") %>% 
  as_tibble()

smts_info <- tibble(filepath = list.files("../Zonation/data/seamounts/all", full.names = T)) %>% 
  mutate(w = sum(spp_info$w)/n())

sum(spp_info$w) ==  sum(smts_info$w)

provs_df <- data.table::fread("data/provs_df.csv") %>% 
  as_tibble()

provs_info <- tibble(filepath = list.files(c("../Zonation/data/biogeography/Spalding",
                                             "../Zonation/data/biogeography/GOODS"), 
                                           full.names = T)) %>% 
  mutate(w = sum(spp_info$w)/n())

sum(spp_info$w) ==  sum(provs_info$w)
```

```{r}
features_df <- spp_df %>% 
  left_join(smts_df) %>% 
  left_join(provs_df)

n_features <- nrow(spp_info)  + nrow(smts_info) + nrow(provs_info) 

feature_names <- colnames(features_df)[c(-1,-2,-3)]
```

## Normalize and trim

```{r}
features_matrix <- features_df %>% 
  select(-x,-y,-cell_id) %>% 
  as.matrix()

stopifnot(
  sum(map_lgl(features_df, is.numeric)) == ncol(features_df) 
  ) # ALL numeric?

Norm_features_matrix <- sweep(features_matrix, 2, colSums(features_matrix, na.rm = T), FUN = "/")

stopifnot(
  sum(colSums(Norm_features_matrix, na.rm = T)) == ncol(features_matrix)
  )  # Normalized OK?

Norm_features_matrix <- Norm_features_matrix[rowSums(is.na(Norm_features_matrix)) != ncol(Norm_features_matrix), , drop = F]

rownames(Norm_features_matrix) <- features_df$cell_id

stopifnot(
  identical(colnames(Norm_features_matrix), 
          features_df %>% 
            select(-x,-y,-cell_id) %>% 
            colnames())
  )  # Is the order of the features mantained?

Norm_features_matrix[is.na(Norm_features_matrix)] <- 0
```

## Feature weights 

```{r}
feature_wts <- c(spp_info$w, smts_info$w, provs_info$w)
  
names(feature_wts) <- feature_names
```

# Current MPAs

```{r}
MPAs <- raster("../Zonation/data/masks/reviewed_all_implemented_MPAs_raster_moll.tif")

MPAs_df <- MPAs %>% 
  raster::as.data.frame(xy = T) %>%
  inner_join(ocean_matrix) %>% 
  select(x, y, cell_id, mpa = reviewed_all_implemented_MPAs_raster_moll) %>%
  as_tibble() 

fraction_in_MPA <- sum(!is.na(MPAs_df$mpa))/nrow(MPAs_df)
  
MPA_vect <- rownames(Norm_features_matrix) %>% 
  enframe() %>% 
  select(cell_id = value) %>% 
  left_join(MPAs_df) %>% 
  mutate(mpa =  !is.na(mpa)) %>% pull(mpa)
```

# Ranking

## With impacts

### Apply Impacts 

```{r}
bio_abatable_impacts_df <- raster("../../../gcs/git-annex/Carta-Marina/Impacts/data/processed/Abatable_impacts_5yr_avg_log.tif") %>% 
  raster::as.data.frame(xy = T) %>% 
  set_names(c("x", "y", "Ia")) %>% 
  inner_join(ocean_matrix) %>% 
  as_tibble() %>% 
  replace_na(list(Ia = 0))

bio_unabatable_impacts_df <- raster("../../../gcs/git-annex/Carta-Marina/Impacts/data/processed/Unbatable_impacts_5yr_avg_log.tif") %>% 
  raster::as.data.frame(xy = T) %>% 
  set_names(c("x", "y", "Iu")) %>% 
  inner_join(ocean_matrix) %>% 
  as_tibble()%>% 
  replace_na(list(Iu = 0))

Norm_features_matrix_BAU <- Norm_features_matrix %>% 
  sweep(1, (1 - bio_abatable_impacts_df$Ia), FUN = "*") %>% 
  sweep(1, (1 - bio_unabatable_impacts_df$Iu), FUN = "*")

remains_BAU <- colSums(Norm_features_matrix_BAU, na.rm = T)

Norm_features_matrix_MPAs <- Norm_features_matrix %>% 
  sweep(1, (1 - bio_unabatable_impacts_df$Iu), FUN = "*")

remains_MPA <- colSums(Norm_features_matrix_MPAs, na.rm = T)

Norm_features_matrix_diff <- Norm_features_matrix %>% 
  sweep(1, (bio_abatable_impacts_df$Ia - bio_abatable_impacts_df$Ia*bio_unabatable_impacts_df$Iu), FUN = "*")
```

```{r}
B_bau <- remains_BAU^0.25

B_mpa <- remains_MPA^0.25

hist(B_bau)

hist(B_mpa)

# How much would remain under BAU?
sum(remains_BAU^0.25)/n_features
# How much would remain with full protection?
sum(remains_MPA^0.25)/n_features
# What is the % increase from
(sum(remains_MPA^0.25) - sum(remains_BAU^0.25))/sum(remains_BAU^0.25)
```

### Initial conditions

```{r}
z <- 0.25

protected_cells <- matrix(MPA_vect, nrow = 1, ncol = nrow(Norm_features_matrix_diff))

colnames(protected_cells) <- rownames(Norm_features_matrix_diff)

unprotected_matrix <- Norm_features_matrix_diff[!protected_cells, ,drop = F]

baseline_state <- remains_BAU + protected_cells%*%Norm_features_matrix_diff

protected_matrix <- Norm_features_matrix_diff[protected_cells, ,drop =F]

max_slopes <- z*baseline_state^(z - 1)
```

### Run algorithm

```{r}
ranking <- list()

current_pick <- 0

current_state <- baseline_state

start_time <- Sys.time()

while(nrow(unprotected_matrix) > 0){
  
  current_pick <- sum(current_pick, 1)
  
  slopes <- feature_wts*pmin(max_slopes, z*current_state^(z - 1))
  
  delta <- unprotected_matrix%*%t(as.matrix(slopes))
  
  best_cell_indeces <- doBy::which.maxn(delta, n = 100)
  
  best_cells <- delta[best_cell_indeces, ] %>% 
    enframe() %>% 
    set_names(c('cell_id', "delta")) %>% 
    mutate(pick_order = current_pick)
  
  ranking <- bind_rows(ranking, best_cells)
  
  current_state <- unprotected_matrix[best_cell_indeces, , drop = F] %>% 
    colSums() +
    current_state
  
  unprotected_matrix <- unprotected_matrix[-best_cell_indeces, , drop = F]
  
}

end_time <- Sys.time()

end_time - start_time

write_rds(ranking, 
          file.path(output_dir, "ranking_results_with_impacts.rds"))
```

# Results

## Benefit Curves

### With Impacts 

```{r}
ranking_with_impacts <- read_rds(file.path(output_dir, "ranking_results_with_impacts.rds"))

benefit_curve_with_impacts <- MPAs_df %>% 
  filter(!is.na(mpa)) %>% 
  select(cell_id) %>% 
  bind_rows(ranking_with_impacts) %>% 
  mutate(is_mpa = is.na(delta))  %>% 
  full_join(ocean_matrix) %>% 
  left_join(Norm_features_matrix_diff %>% 
              as_tibble(rownames = NA) %>% 
              rownames_to_column("cell_id")) %>% 
  replace(is.na(.), 0) %>% 
  select(-x, -y, -delta, -pick_order, -is_mpa) %>% 
  mutate(cell_id = as.numeric(cell_id)) %>% 
  mutate_at(vars(-cell_id),.funs = cumsum) %>% 
  sweep(MARGIN = 2, c(0, remains_BAU), `+`) %>%
  mutate_at(vars(-cell_id), .funs = ~(.)^0.25) 

write_rds(benefit_curve_with_impacts, 
          file.path(output_dir, "bio_benefit_curves.rds"))

benefit_curve_with_impacts %>% 
  select(-cell_id) %>% 
  as.matrix() %*% as.matrix(feature_wts) %>% 
  #rowSums() %>% 
  as_tibble() %>% 
  set_names("V") %>% 
  mutate(fraction_protected = 1/n(),
         fraction_protected = cumsum(fraction_protected)) %>% 
  filter(fraction_protected > fraction_in_MPA) %>% 
  ggplot()+
  geom_line(aes(x = fraction_protected, y = V/sum(feature_wts))) +
  geom_vline(xintercept = c(0.1, 0.2, 0.3),
             linetype = c("dashed","dotted","dotdash"))+
  labs(x = "Fraction Ocean Protected",
       y = "Biodiversity Benefit",
       caption = "Biodiversity national, with impacts, Juanation")+
  theme_classic()+
  scale_x_continuous(limits = c(0,1), expand = c(0,0))+
  geom_rect(aes(xmin = 0, 
                xmax = fraction_in_MPA, 
                ymin = min(benefit_curve_with_impacts$V)/sum(feature_wts), 
                ymax = max(benefit_curve_with_impacts$V)/sum(feature_wts)),
                fill = "#69B578", alpha = 0.01)+
  ggsave(file.path(figs_output_dir, "benefit_curve_with_impacts.png"),
         width = 7, height = 4)
```

```{r}
representation_curves_with_impacts <- MPAs_df %>% 
  filter(!is.na(mpa)) %>% 
  select(cell_id) %>% 
  bind_rows(ranking_with_impacts) %>% 
  mutate(is_mpa = is.na(delta))   %>% 
  full_join(ocean_matrix) %>% 
  left_join(Norm_features_matrix %>% 
              as_tibble(rownames = NA) %>% 
              rownames_to_column("cell_id")) %>% 
  replace(is.na(.), 0) %>% 
  select(-x, -y, -cell_id, -delta, -pick_order, -is_mpa) %>% 
  mutate_all(.funs = cumsum) 
  
write_rds(representation_curves_with_impacts, 
          file.path(output_dir, "representation_curves_with_impacts.rds"))

representation_curves_with_impacts %>% 
  as.matrix() %>% 
  rowSums() %>% 
  as_tibble() %>% 
  set_names("V") %>% 
  mutate(fraction_protected = 1/n(),
         fraction_protected = cumsum(fraction_protected)) %>% 
  mutate(V = V/n_features) %>% 
  filter(fraction_protected > fraction_in_MPA) %>% 
  ggplot()+
  geom_line(aes(x = fraction_protected, y = V)) +
  geom_vline(xintercept = c(0.1, 0.2, 0.3),
             linetype = c("dashed","dotted","dotdash"))+
  labs(x = "Fraction Ocean Protected",
       y = "Average feature representation",
       caption = "Biodiversity + MPAs, with impacts, Juanation")+
  theme_classic()+
  scale_x_continuous(limits = c(0,1), expand = c(0,0))+
  geom_rect(aes(xmin = 0, 
                xmax = fraction_in_MPA, 
                ymin = 0,
                ymax = 1),
                fill = "#69B578", alpha = 0.01)+
  ggsave(file.path(figs_output_dir, "representation_curve_with_impacts.png"),
         width = 7, height = 5)
```

## Priority Maps

```{r}
ranking_raster_with_impacts <- MPAs_df %>% 
  filter(!is.na(mpa)) %>% 
  select(cell_id) %>% 
  bind_rows(ranking_with_impacts) %>% 
  mutate(is_mpa = is.na(delta)) %>% 
  left_join(ocean_matrix) %>% 
  tibble::rowid_to_column("ID") %>% 
  mutate(rank = 1- scales::rescale(ID)) %>% 
  select(x, y, rank) %>% 
  rasterFromXYZ(crs = crs(ocean_low_res_moll)) %>% 
  projectRaster(ocean_low_res_moll) %>% 
  mask(ocean_low_res_moll) 

writeRaster(ranking_raster_with_impacts, 
            file.path(output_dir, "ranking_raster_with_impacts.tif"), 
            overwrite = T)
```

```{r}
ranking_map_with_impacts <- tmap::tm_shape(ranking_raster_with_impacts)+
  tmap::tm_raster(title = "",
                  palette  = z_pal$colors,
                  breaks = z_pal$breaks,
                  labels = z_pal$labels,
                  legend.is.portrait = T, 
                  legend.reverse = T)+
  tmap::tm_shape(land_shp_moll)+
  tmap::tm_fill(col = "black", border.col = "transparent")+
  tmap::tm_credits("sBiodiversity + MPAs, with impacts") +
  tmap::tm_shape(MPAs)+
  tmap::tm_raster(col = "reviewed_all_implemented_MPAs_raster_moll", palette = "#00A600FF", legend.show	= F)+
  tmap::tm_layout(title = "Biodiversity Conservation Priorities",
                  title.position = c("center", .95),
                  inner.margins = c(0.12, 0, 0.08, 0.04), 
                  frame = F,
                  legend.position = c(.99, "center")) 

tmap::tmap_save(ranking_map_with_impacts, 
                filename = file.path(figs_output_dir, "priority_map_with_impacts.png"),
                dpi = 300,  height = 4, width = 8 )
```

# Where would upgrading weak MPAs take us?

```{r}
bio_benefit_curves_upgrade_MPAs <- read_rds(file.path(output_dir, "bio_benefit_curves.rds"))
bio_benefit_curves_today_MPAs <- read_rds("05_spp_wts_smts_provs_MPAs/results/bio_benefit_curves.rds")

bio_curve_upgrade <- bio_benefit_curves_upgrade_MPAs %>% 
  select(-cell_id) %>% 
  as.matrix() %*% as.matrix(feature_wts) %>% 
  as_tibble() %>% 
  set_names("V") %>% 
  mutate(fraction_protected = 1/n(),
         cell_id = bio_benefit_curves_upgrade_MPAs$cell_id,
         fraction_protected = cumsum(fraction_protected),
         V_rescaled = scales::rescale(V))

bio_curve_today <- bio_benefit_curves_today_MPAs %>% 
  select(-cell_id) %>% 
  as.matrix() %*% as.matrix(feature_wts) %>% 
  as_tibble() %>% 
  set_names("V") %>% 
  mutate(fraction_protected = 1/n(),
         cell_id = bio_benefit_curves_today_MPAs$cell_id,
         fraction_protected = cumsum(fraction_protected),
         V_rescaled = scales::rescale(V))

full_join(bio_curve_today %>% 
            filter(fraction_protected > 0.024) %>% 
            select(fraction_protected, current_protection = V_rescaled),
          bio_curve_upgrade %>% 
            filter(fraction_protected > fraction_in_MPA) %>% 
            select(fraction_protected, upgrade_protection = V_rescaled)) %>% 
  gather(var, val, -fraction_protected) %>% 
  ggplot()+
  geom_line(aes(x = fraction_protected, y = val, col = var))+
  labs(x = "Fraction Ocean Protected",
       y = "Biodiversity benefit",
       col = "")+
  theme_classic()+
  scale_color_discrete(labels = c("current", "upgraded"))+
  scale_x_continuous(expand = c(0,0), labels = c(0,0.25,0.5,0.75,1))+
  scale_y_continuous(expand = c(0,0), labels = c(0,0.25,0.5,0.75,1))+
  expand_limits(y = c(0, 1.1),
                x = c(0, 1))+
    ggsave(filename = file.path(DIR_GCS, "Supplement/fig_upgraded_MPAs_bio_benefit.png"), 
         dpi = 300,  height = 5, width = 8)
```

```{r}
bio_curve_today %>% 
  filter(fraction_protected < 0.024) %>% 
  slice(which.max(V_rescaled))

bio_curve_upgrade %>% 
  filter(fraction_protected < fraction_in_MPA) %>% 
  slice(which.max(V_rescaled))
```



# What does it take to get 90% of the benefits?

```{r}
bio_benefit_curves <- read_rds(file.path(output_dir, "bio_benefit_curves.rds")) 

agg_bio_benefit_curve <- bio_benefit_curves %>% 
  select(-cell_id) %>% 
  as.matrix() %*% as.matrix(feature_wts) %>% 
  as_tibble() %>% 
  set_names("V") %>% 
  mutate(fraction_protected = 1/n(),
         fraction_protected = cumsum(fraction_protected),
         V_rescaled = scales::rescale(V))

(f_to_90 <- agg_bio_benefit_curve %>% 
  slice(which.min(abs(V_rescaled - 0.9))) %>% 
  pull(fraction_protected))
```

How much in EEZ vs HS? 

```{r}
eez_mask <- raster("../../../gcs/git-annex/Carta-Marina/masks/data/processed/EEZ_mask.tif") # 1 equals high seas

eez_mask_df_moll <- eez_mask %>% 
  as.data.frame(xy = TRUE) %>% 
  set_names(c("x", "y", "eez_mask")) %>% 
  mutate(eez_mask = ifelse(eez_mask == 1, 1, NA)) %>% 
  filter(!is.na(eez_mask)) %>% 
  inner_join(ocean_matrix)
```


```{r}
agg_bio_benefit_curve %>% 
  mutate(cell_id = bio_benefit_curves$cell_id,
         in_EEZ = cell_id %in% eez_mask_df_moll$cell_id) %>% 
  summarize(f_EEZ_to_90 = length(V[in_EEZ & fraction_protected <= f_to_90])/length(V[in_EEZ]),
            f_HS_to_90 = length(V[!in_EEZ & fraction_protected <= f_to_90])/length(V[!in_EEZ]))
```

# How much of the top 10% is in EEZ?

```{r}
agg_bio_benefit_curve %>% 
  mutate(cell_id = bio_benefit_curves$cell_id,
         in_EEZ = cell_id %in% eez_mask_df_moll$cell_id) %>% 
  filter(fraction_protected <= 0.1) %>% 
  group_by(in_EEZ) %>% 
  summarise(n_cells = n()) %>% 
  ungroup() %>% 
  mutate(f_cell = n_cells/sum(n_cells))
```
