---
title: "Food provision in Juanation"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r, message = FALSE}
library(raster)
library(sf)
library(tidyverse)
library(patchwork)

source(here::here("common.R"))

variant_name <- "16_food_alternative_effort_models"

variant_dir <- file.path(emLab_project_dir,"data", "03_output", variant_name)

dir.create(variant_dir)
```

# Load  data 

```{r, eval = F}
stocks <- tibble(filename = list.files(file.path(emLab_project_dir, "data", "02_processed", "stock_distributions"),
                                       full.names = T),
                 stockid = str_remove(basename(filename), "\\.tif"))

stocks_df <- stack(stocks$filename) %>%
  raster::as.data.frame(xy = T) %>%
  inner_join(ocean_matrix) %>% 
  select(x, y, cell_id, everything()) %>%
  as_tibble() 

data.table::fwrite(stocks_df, 
                   file.path(emLab_project_dir, "data", "02_processed", "features_df", "stocks_df.csv"))
```

```{r}
stocks <- tibble(filename = list.files(file.path(emLab_project_dir, "data", "02_processed", "stock_distributions"),
                                       full.names = T),
                 stockid = str_remove(basename(filename), "\\.tif"))

stocks_info <- read_csv(file.path(emLab_project_dir,"data", "02_processed", "food_provision", "MegaData_UncertaintyAnalysis.csv")) %>%
  select(stockid, k = Kfin, ex_rate = ExploitationRate_BAU1, m = m_fin, r = r_fin)

stocks_info <- stocks %>%
  left_join(stocks_info)

stocks_df <- data.table::fread(file.path(emLab_project_dir, "data", "02_processed", "features_df", "stocks_df.csv")) %>% 
  as_tibble()
```

```{r}
identical(stocks_info$stockid , str_replace_all(names(stocks_df)[-c(1,2,3)], "\\.", "-"))
```

## Normalize and trim

```{r}
features_matrix <- stocks_df %>%
  select(-x,-y,-cell_id) %>% 
  as.matrix()

stopifnot(
  sum(map_lgl(stocks_df %>%
                select(-x,-y,-cell_id), is.numeric)) == ncol(features_matrix)
  ) # ALL numeric?

Norm_features_matrix <- sweep(features_matrix, 2, colSums(features_matrix, na.rm = T), FUN = "/")

rownames(Norm_features_matrix) <- stocks_df$cell_id

stopifnot(
  sum(colSums(Norm_features_matrix, na.rm = T)) == ncol(features_matrix)
  )  # Normalized OK?

Norm_features_matrix <- Norm_features_matrix[rowSums(is.na(Norm_features_matrix)) != ncol(Norm_features_matrix), ]

stopifnot(
  identical(colnames(Norm_features_matrix), 
          stocks_df %>% 
            select(-x,-y,-cell_id) %>% 
            colnames())
  )  # Is the order of the features mantained?
```

# Current MPAs

```{r}
MPAs <- raster(file.path(emLab_project_dir, "data", "02_processed", "masks", "fully_highly_protected_reviewed_MPAs.tif"))

MPAs_df <- MPAs %>% 
  raster::as.data.frame(xy = T) %>%
  inner_join(ocean_matrix) %>% 
  select(x, y, cell_id, mpa = fully_highly_protected_reviewed_MPAs) %>%
  as_tibble() 

fraction_in_MPA <- sum(!is.na(MPAs_df$mpa))/nrow(MPAs_df)
  
MPA_vect <- rownames(Norm_features_matrix) %>% 
  enframe() %>% 
  select(cell_id = value) %>% 
  left_join(MPAs_df) %>% 
  mutate(mpa =  !is.na(mpa)) %>% pull(mpa)
```

# Ranking 

```{r}
Norm_features_matrix[is.na(Norm_features_matrix)] <- 0

protected_cells <- matrix(MPA_vect, nrow = 1, ncol = nrow(Norm_features_matrix))

colnames(protected_cells) <- rownames(Norm_features_matrix)

baseline_state <- protected_cells%*%Norm_features_matrix

stocks_info$ex_rate[stocks_info$ex_rate >= 1] <- 0.99999
```

## Effort goes outside

### functions

```{r}
estimate_slopes_a1 <- function(e = stocks_info$ex_rate, 
                               m = stocks_info$m,
                               r = stocks_info$r, 
                               k = stocks_info$k, 
                               R){
  
  A <- (1 - e)^(1/(1 - R))
  
  part_a <- A*log(1 - e)*k*m*(1 - (1 - A)*m*(1 - R)/(r*((1 - A)*R + m)))/((1 - R)*((1 - A)*R + m))
  
  part_b <- (1 - A)*k*m*(1 - (1 - A)*m*(1 - R)/(r*((1 - A)*R + m)))/((1 - A)*R + m)
  
  part_c <- (1 - A)*k*m*(1 - R)*(- A*log(1 - e)*R/(1 - R)^2 - A + 1)*(1 - (1 - A)*m*(1 - R)/(r*((1 - A)*R + m)))/((1 - A)*R + m)^2
  
  part_d <- (1 - A)*k*m*(1 - R)*(A*log(1 - e)*m/(r*(1 - R)*((1 - A)*R + m)) + (1 - A)*m/(r*((1 - A)*R + m)) + (1 - A)*m*(1 - R)*(-A*log(1 - e)*R/(1 - R)^2 - A + 1)/(r*((1 - A)*R + m)^2))/((1 - A)*R + m)
  
  slope <- - part_a - part_b - part_c + part_d
  
  return(slope)
  
}

estimate_delta_catch_a1 <- function(x, 
                                    e = stocks_info$ex_rate, 
                                    m = stocks_info$m,
                                    r = stocks_info$r, 
                                    k = stocks_info$k) {
  
  R_bau <- 0
  
  x[x > 1] <- 1 
  
  exp_rate <- 1 - (1 - e)^(1/(1 - x))
  
  part_a <- exp_rate*(m*k)*(1 - x)/(exp_rate*x + m)*(1 - exp_rate*(1 - x)*m/((exp_rate*x + m)*r))
  
  part_b <- e*(m*k*(1 - R_bau)/(e*R_bau + m)*(1 - e*(1 - R_bau)*m/((e*R_bau + m)*r)))
  
  return(part_a - part_b)
  
}
```

### run algorithm

```{r}
unprotected_matrix <- Norm_features_matrix[!protected_cells, ]

protected_matrix <- Norm_features_matrix[protected_cells, ]

ranking <- list()

current_pick <- 0

current_state <- baseline_state 

start_time <- Sys.time()

while(nrow(unprotected_matrix) > 0){
  
  current_pick <- sum(current_pick, 1)
  
  slopes <- estimate_slopes_a1(R = current_state)
  
  slopes[is.na(slopes)] <- 0

  delta <- unprotected_matrix%*%as.matrix(t(slopes))
  
  best_cell_indeces <- doBy::which.maxn(delta, n = 100)
  
  best_cells <- delta[best_cell_indeces,] %>% 
    enframe() %>% 
    set_names(c('cell_id', "delta")) %>% 
    mutate(pick_order = current_pick)
  
  ranking <- bind_rows(ranking, best_cells)
  
  current_state <- unprotected_matrix[best_cell_indeces, ] %>% 
    colSums() +
    current_state
  
  unprotected_matrix <- unprotected_matrix[-best_cell_indeces, ]
  
}

end_time <- Sys.time()

end_time - start_time

write_rds(ranking,
          file.path(variant_dir, "ranking_results_a1.rds"))
```

# Results

## benefit curve

```{r}
ranking <- read_rds(file.path(variant_dir, "ranking_results_a1.rds"))

ranked_rep_levels <- MPAs_df %>% 
  filter(!is.na(mpa)) %>% 
  select(cell_id) %>% 
  bind_rows(ranking) %>% 
  mutate(is_mpa = is.na(delta)) %>% 
  full_join(ocean_matrix) %>% 
  left_join(Norm_features_matrix %>% 
              as_tibble(rownames = NA) %>% 
              rownames_to_column("cell_id")) %>% 
  replace(is.na(.), 0)

network_delta_catch_per_stock <- ranked_rep_levels %>% 
  select(-x, -y, -cell_id, -delta, -pick_order, -is_mpa) %>% 
  mutate_all(.funs = cumsum) %>% 
  apply(MARGIN = 1, estimate_delta_catch_a1)  %>% 
  t() 

network_delta_catch <- network_delta_catch_per_stock %>% 
  rowSums() %>% 
  enframe() 
  
pixel_delta_catch <- ranked_rep_levels %>%
  select(-x, -y, -cell_id, -delta, -pick_order, -is_mpa) %>%
  apply(MARGIN = 1, estimate_delta_catch_a1)  %>% 
  t() %>%
  rowSums() %>%
  enframe()

results_per_pixel <- ranked_rep_levels %>% 
  select(x, y, is_mpa) %>% 
  cbind(pixel_delta_catch = pixel_delta_catch$value,
        network_cummulative_delta_catch = network_delta_catch$value) %>% 
  mutate(pixel_contribution_to_network = network_cummulative_delta_catch - lag(network_cummulative_delta_catch),
         pixel_contribution_to_network = if_else(is.na(pixel_contribution_to_network), network_cummulative_delta_catch, pixel_contribution_to_network)) 

write_csv(results_per_pixel, 
          file.path(variant_dir, "results_per_pixel_a1.csv"))

network_delta_catch_per_stock %>% 
  as_tibble() %>% 
  mutate(cell_id = ranked_rep_levels$cell_id) %>%
  select(cell_id, everything()) %>% 
  write_rds(file.path(variant_dir, "network_delta_catch_per_stock_a1.rds"))
```

```{r}
network_delta_catch %>% 
  mutate(fraction_protected = 1/n(),
         fraction_protected =  cumsum(fraction_protected)) %>% 
  filter(fraction_protected > fraction_in_MPA) %>% 
  ggplot()+
  geom_line(aes(fraction_protected, value))+
  labs(x = "Fraction Ocean Protected",
       y = "Delta Catch",
       caption = "a1, all effort is displaced") +
  theme_classic()+
  geom_rect(aes(xmin = 0, 
                xmax = fraction_in_MPA, 
                ymin = min(network_delta_catch$value), 
                ymax = max(network_delta_catch$value)),
                fill = "#69B578", alpha = 0.01)+
  scale_x_continuous(limits = c(0,1), expand = c(0, 0))+
  scale_y_continuous(expand = c(0, 100))+
  ggsave(file.path(variant_dir, "delta_catch_curve_a1.png"),
         width = 7, 
         height = 4)

results_per_pixel %>% 
  mutate(fraction_protected = 1/n(),
         fraction_protected =  cumsum(fraction_protected)) %>% 
  ggplot()+
  geom_line(aes(fraction_protected, pixel_contribution_to_network))+
  labs(x = "Fraction Ocean Protected",
       y = "Delta Catch",
       caption = "Juanation")+
  theme_minimal()
```

## max delta catch

```{r}
max(network_delta_catch$value, na.rm = T)/10^6

bau_delta_catch <- network_delta_catch %>% 
  mutate(fraction_protected = 1/n(),
         fraction_protected =  cumsum(fraction_protected)) %>% 
  filter(fraction_protected <= fraction_in_MPA) %>% 
  summarise(current_delta_catch = max(value)) %>% pull()

(max_delta_catch <- max(network_delta_catch$value, na.rm = T) - bau_delta_catch)/10^6

optimal_protection_level <- network_delta_catch %>% 
  mutate(fraction_protected = 1/n(),
         fraction_protected =  cumsum(fraction_protected)) %>% 
  filter(value == max(network_delta_catch$value)) %>% 
  pull(fraction_protected)
```

```{r}
diff_90 <- bau_delta_catch + 0.9*(max_delta_catch)

results_per_pixel %>% 
  mutate(fraction_protected = 1/n(),
         fraction_protected =  cumsum(fraction_protected)) %>% 
  filter(fraction_protected < optimal_protection_level,
         fraction_protected > fraction_in_MPA) %>% 
  slice(which.min(abs(network_cummulative_delta_catch - diff_90))) %>% 
  pull(fraction_protected)
```

## maps

### global ranking

```{r}
ranking_raster <- MPAs_df %>% 
  filter(!is.na(mpa)) %>% 
  select(cell_id) %>% 
  bind_rows(ranking) %>% 
  mutate(is_mpa = is.na(delta)) %>% 
  left_join(ocean_matrix) %>% 
  tibble::rowid_to_column("ID") %>% 
  mutate(rank = 1- scales::rescale(ID)) %>% 
  select(x, y, rank) %>% 
  rasterFromXYZ(crs = crs(ocean_low_res_moll)) %>% 
  projectRaster(ocean_low_res_moll) %>% 
  mask(ocean_low_res_moll) 

writeRaster(ranking_raster, 
            file.path(variant_dir, "ranking_raster.tif"), 
            overwrite = T)

ranking_map <- tmap::tm_shape(ranking_raster)+
  tmap::tm_raster(title = "",
                  palette  = priorities_map_pal$colors,
                  breaks = priorities_map_pal$breaks,
                  labels = priorities_map_pal$labels,
                  legend.is.portrait = T, 
                  legend.reverse = T)+
  tmap::tm_shape(land_50_moll)+
  tmap::tm_fill(col = "black", border.col = "transparent")+
  tmap::tm_credits("Food") +
  tmap::tm_shape(MPAs)+
  tmap::tm_raster(col = "fully_highly_protected_reviewed_MPAs", palette = "#00A600FF", legend.show	= F)+
  tmap::tm_layout(title = "Food Provision Conservation Priorities",
                  title.position = c("center", .95),
                  inner.margins = c(0.12, 0, 0.08, 0.04), 
                  frame = F,
                  legend.position = c(.99, "center")) 

tmap::tmap_save(ranking_map, 
                filename = file.path(variant_dir, "priority_map.png"),
                dpi = 300,  height = 4, width = 8 )
```

### optimal food protection map

```{r}
optimal_protection_map <- ranking_raster %>% 
  mask(ranking_raster >= (1 - optimal_protection_level), maskvalue = 0) %>% 
  tmap::tm_shape()+
  tmap::tm_raster(title = "",
                  palette = rev("-Spectral"), 
                  n = 20,
                  
                  style = "cont",
                  legend.is.portrait = T, 
                  legend.reverse = T)+
  tmap::tm_shape(land_50_moll)+
  tmap::tm_fill(col = "grey", border.col = "transparent")+
  tmap::tm_credits("Food") +
  tmap::tm_shape(MPAs)+
  tmap::tm_raster(col = "fully_highly_protected_reviewed_MPAs", palette = "#00A600FF", legend.show	= F)+
  tmap::tm_layout(title = "Food Provision Conservation Priorities",
                  title.position = c("center", .95),
                  inner.margins = c(0.12, 0, 0.08, 0.04), 
                  frame = F,
                  legend.position = c(.99, "center"))

tmap::tmap_save(optimal_protection_map, 
                filename = file.path(variant_dir, "optimal_protection_map.png"),
                dpi = 300,  height = 4, width = 8 )
```

### pixel contribution to network

```{r}
results_per_pixel %>% 
  mutate(tmp = abs(pixel_contribution_to_network)^(1/3),
         tmp_2 = ifelse(pixel_contribution_to_network < 0, -tmp, tmp)) %>% 
  ggplot()+
  geom_raster(aes(x, y, fill = tmp_2))+
  scale_fill_gradient2(labels = function(x){x^3},
                       low = "darkred", mid = "white",
                            high = "navy", space = "Lab")+
  labs(title = "Change in global catch (Tonnes)", fill = "", y = "", x = "")+
  theme_minimal()+
  ggsave(file.path(variant_dir, "pixel_contribution_map.png"),dpi = 300,  height = 4, width = 8)
```

## max changes in catch per stock

```{r}
cells_per_stock <- ranked_rep_levels %>% 
  select(-x, -y, -cell_id, -delta, -pick_order, -is_mpa) %>% 
  summarize_all(~sum(.x > 0)) %>% 
  pivot_longer(everything(), names_to = "stockid", values_to = "n_cells")

network_delta_catch_per_stock_a1 <- read_rds(file.path(variant_dir, "network_delta_catch_per_stock_a1.rds"))

max_catch_per_stock_a1 <- network_delta_catch_per_stock_a1 %>% 
  select(-cell_id) %>% 
  summarize_all(max) %>% 
  pivot_longer(everything(), names_to = "stockid", values_to = "max_delta_catch_a1") 

network_delta_catch_per_stock_a0 <- read_rds("~/Google Drive File Stream/Shared drives/emlab/projects/current-projects/ocean-conservation-priorities/data/03_output/07_food/network_delta_catch_per_stock.rds")

max_catch_per_stock_a0 <- network_delta_catch_per_stock_a0 %>% 
  select(-cell_id) %>% 
  summarize_all(max) %>% 
  pivot_longer(everything(), names_to = "stockid", values_to = "max_delta_catch_a0") 

comparing_assumptions <- max_catch_per_stock_a1 %>% 
  left_join(max_catch_per_stock_a0) %>% 
  left_join(cells_per_stock, by = "stockid") %>% 
  mutate(stockid = str_replace_all(stockid, "\\.", "-")) %>% 
  left_join(stocks_info %>% select(-filename), by = "stockid")

comparing_assumptions %>% write_csv(file.path(variant_dir, "max_delta_catch_per_stock.csv"))
```

```{r}
comparing_assumptions <- read_csv(file.path(variant_dir, "max_delta_catch_per_stock.csv"))

comparing_assumptions %>% 
  mutate(diff = max_delta_catch_a1 - max_delta_catch_a0,
         diff_n = ifelse(diff < 0, -abs(diff)^(1/3), abs(diff)^(1/3)),
         percent_change = 100*(max_delta_catch_a1 - max_delta_catch_a0)/max_delta_catch_a0,
         m = as.factor(m)) %>%
  ggplot()+
  geom_point(aes(x = n_cells, y = diff_n, col = k, shape = m))+
  scale_x_log10()+
  labs(y = "Difference in delta H (cubic root transform)", x  = "stock range size (log 10 # of cells)")
  
  comparing_assumptions %>% 
  mutate(diff = max_delta_catch_a1 - max_delta_catch_a0,
         diff_n = ifelse(diff < 0, -abs(diff)^(1/3), abs(diff)^(1/3)),
         percent_change = 100*(max_delta_catch_a1 - max_delta_catch_a0)/max_delta_catch_a0,
         m = as.factor(m)) %>%
  ggplot()+
  geom_point(aes(x = ex_rate, y = diff_n, col = k, shape = m))+
  labs(y = "Difference in delta H (cubic root transform)", x  = "Exploitation rate")
```

```{r}
sum(comparing_assumptions$max_delta_catch_a0)/10^6

sum(comparing_assumptions$max_delta_catch_a1)/10^6
```

